Improve unix command history plugin
fox-it/dissect.target pull request #110
Opened 2022-12-28 10:26 UTC by JSCU-CNI

This patch makes the bashhistory unix function shell-agnostic.

2023-01-06 15:06 UTC, pyrco commented
Hi, thanks for the nice extension of the commandhistory plugin!

Before it can be merged in however, some changes need to be made to the `RecordDescriptorExtention` used for the `_user` parameter of the `CommandHistoryRecord`.

The design/idea behind this extension field is that it is uniform across different OSes and lightweight on information to prevent to much data duplication in the output. As you can imagine the latter is of course a balance, hence the inclusion of e.g. `user_home`. Any other information can be enriched by correlating these records with the output of the users plugin. So this means using a `UnixUserRecordDescriptorExtension` for the `_user` parameter is unfortunately not what should be done.

We discussed internally and agreed that adding a `user_group` field to the `UserRecordDescriptorExtension` class in `helpers/descripter_extensions.py` which contains the id of the main group of the user should not extend the `UserRecordDescriptorExtension`  too much. So please implement it there. For now it is ok to leave the value for `user_group` as `None` on windows based systems.

2023-01-09 08:32 UTC, pyrco requested changes

2023-01-09 08:32 UTC, pyrco commented on dissect/target/helpers/descriptor_extensions.py
> +class UnixUserRecordDescriptorExtension(RecordDescriptorExtensionBase):
See earlier comment

2023-01-09 16:22 UTC, JSCU-CNI commented
Thank you for your comment @pyrco. I added `user_group` to the generic `UserRecordDescriptorExtension`.

Could you clarify why `WindowsUserRecord` and `UnixUserRecord` exist in `dissect/target/helpers/record.py`? It seems to me that per your rhetoric they should be merged into a single `UserRecordDescriptorExtension`.

2023-01-10 10:25 UTC, pyrco requested changes

2023-01-10 10:25 UTC, pyrco commented on dissect/target/plugins/os/unix/commandhistory.py
> +                    for line in file_.open("rt", errors="ignore"):  # Ignore Non-ASCII characters in bash_history
```suggestion
                    for line in file_.open("rt", errors="ignore"):  # Ignore Non-UTF-8 characters in bash_history
```

Wouldn't it be better to use `errors="replace"` so you know you are potentially missing something?

2023-01-10 10:25 UTC, pyrco commented on dissect/target/plugins/os/unix/commandhistory.py
> +        return self.commandhistory()
```suggestion
        warnings.warn("bashhistory is deprecated, use the commandhistory function", DeprecationWarning)
        return self.commandhistory()
```

2023-01-16 10:48 UTC, JSCU-CNI commented
We added proper support for timestamps in bash history files per the `HISTTIMEFORMAT` setting (https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-HISTTIMEFORMAT). Support for Zsh timestamps is not yet implemented.

2023-01-16 18:41 UTC, pyrco commented
I saw it, nice! It is much cleaner this way.

2023-01-18 09:10 UTC, pyrco approved these changes

2023-01-18 09:34 UTC, pyrco requested changes
_Could you rebase this patch set on the current main branch? There appear to be some conflicting changes. Once rebased, I'll merge it in._

Nevermind, I, merged main cleanly into the branch.

2023-01-18 09:37 UTC, pyrco approved these changes

2023-01-18 09:44 UTC, merged