Fix windows sam parsing
fox-it/dissect.target pull request #121
Opened 2023-01-09 13:55 UTC by JSCU-CNI

This fix depends on fox-it/dissect.regf#9.

2023-01-09 14:11 UTC, Schamper commented
Also fixes https://github.com/fox-it/dissect/issues/17

2023-01-18 15:44 UTC, Schamper requested changes

2023-01-18 15:44 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +        """Returns the classname of this key."""
```suggestion
        """Returns the class name of this key."""
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +
```suggestion
```
Perhaps better to do this as just a constructor argument to `VirtualKey`. See the other suggestion.

2023-01-18 15:44 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +        self._class_name: str = None
```suggestion
    def __init__(self, hive: RegistryHive, path: str, class_name: Optional[str] = None):
        self._path: str = path
        self._name: str = path.split("\\")[-1]
        self._class_name: str = class_name
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +            raise PluginError(f"Unsupported Domain Account F revision encountered: {f.revision}")
```suggestion
            raise ValueError(f"Unsupported Domain Account F revision encountered: {f.revision}")
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +            raise PluginError(f"Unsupported SAM Key Data revision encountered: {fk.revision}")
```suggestion
            raise ValueError(f"Unsupported SAM Key Data revision encountered: {fk.revision}")
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +                raise PluginError("SAM key checksum validation failed!")
```suggestion
                raise ValueError("SAM key checksum validation failed!")
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +from Crypto.Hash import MD5, SHA256
Can you use `hashlib` for the MD5 and SHA256 calculations?

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +                raise PluginError("SAM key checksum validation failed!")
```suggestion
                raise ValueError("SAM key checksum validation failed!")
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    def expand_des_key(key: bytes) -> bytes:
Could you move this to the global scope and out of the class?

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    def rid_to_key(rid: int) -> Tuple[bytes, bytes]:
Could you move this to the global scope and out of the class?

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    def rid_to_key(rid: int) -> Tuple[bytes, bytes]:
```suggestion
    def rid_to_key(rid: int) -> tuple[bytes, bytes]:
```
Also small suggestion to go with that :)

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    def perform_aes(key: bytes, value: bytes, iv: bytes) -> bytes:
Could you move this to the global scope and out of the class? And maybe rename to `aes_crypt` or `aes_decrypt`.

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    def decrypt_single_hash(rid: int, samkey: bytes, enc_hash: bytes, apwd: bytes) -> bytes:
Could you move this to the global scope and out of the class?

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +            raise PluginError(f"Unsupported LM/NT hash revision encountered: {sh.revision}")
```suggestion
            raise ValueError(f"Unsupported LM/NT hash revision encountered: {sh.revision}")
```

2023-01-18 15:44 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +        for users_key in self.target.registry.iterkeys(f"{self.SAM_KEY}\\Users"):
```suggestion
        for users_key in self.target.registry.keys(f"{self.SAM_KEY}\\Users"):
```

2023-01-19 12:30 UTC, Schamper commented
Can you change the dependency on `dissect.regf` in `setup.py` to be:
```
"dissect.regf>=3.3.dev,<4.0.dev",
```

2023-01-19 13:00 UTC, Schamper requested changes

2023-01-19 13:00 UTC, Schamper commented on dissect/target/plugins/os/windows/sam.py
> +    return plaintext
Isn't this the same as:
```python
return AES.new(key, AES.MODE_CBC, iv).decrypt(value)
```

I believe pycryptodome does the block loop automatically.

2023-01-19 13:00 UTC, Schamper commented on tests/test_plugins_os_windows_sam.py
> +from dissect.target.plugins.os.windows.sam import SamPlugin
```suggestion
from flow.record.fieldtypes import datetime as dt

from dissect.target.helpers.regutil import VirtualKey

try:
    from Crypto.Hash import MD4
    from dissect.target.plugins.os.windows.sam import SamPlugin
    
    HAVE_CRYPTO = True
except ImportError:
    HAVE_CRYPTO = False
```

2023-01-19 13:00 UTC, Schamper commented on tests/test_plugins_os_windows_sam.py
> +
```suggestion
@pytest.mark.skipif(not HAVE_CRYPTO, reason="requires pycryptodome")
def test_sam_plugin_rev2(target_win_users, hive_hklm):
```

2023-01-19 15:55 UTC, Schamper commented
I tried to push some final changes myself but it didn't let me, I guess the checkbox to do so wasn't ticked for this PR?

Could you apply these final changes? It's to add `pycryptodome` to the `[full]` install of `dissect.target`, fixing the tests and a small style change in the test:

```diff
diff --git a/setup.py b/setup.py
index 275d82f..f488694 100644
--- a/setup.py
+++ b/setup.py
@@ -79,6 +79,7 @@ setup(
             "dissect.xfs>=3.0.dev,<4.0.dev",
             "ipython",
             "fusepy",
+            "pycryptodome",
             "pyyaml",
             "yara-python",
             # dissect.target's caching uses flow.record functionlity which depends on the
diff --git a/tests/test_plugins_os_windows_sam.py b/tests/test_plugins_os_windows_sam.py
index aa15bc8..bb952b6 100644
--- a/tests/test_plugins_os_windows_sam.py
+++ b/tests/test_plugins_os_windows_sam.py
@@ -1,22 +1,24 @@
+import pytest
 from flow.record.fieldtypes import datetime as dt
 
 from dissect.target.helpers.regutil import VirtualKey
 
 try:
     from Crypto.Hash import MD4
+
     from dissect.target.plugins.os.windows.sam import SamPlugin
-    
+
     HAVE_CRYPTO = True
 except ImportError:
     HAVE_CRYPTO = False
 
-sam_key_name = "SAM\\SAM\\Domains\\Account"
-system_key_name = "SYSTEM\\ControlSet001\\Control\\LSA"
+SAM_KEY_PATH = "SAM\\SAM\\Domains\\Account"
+SYSTEM_KEY_PATH = "SYSTEM\\ControlSet001\\Control\\LSA"
 
 
 @pytest.mark.skipif(not HAVE_CRYPTO, reason="requires pycryptodome")
 def test_sam_plugin_rev1(target_win_users, hive_hklm):
-    sam_key = VirtualKey(hive_hklm, sam_key_name)
+    sam_key = VirtualKey(hive_hklm, SAM_KEY_PATH)
     sam_key.add_value(
         "F",
         bytes.fromhex(
@@ -107,10 +109,10 @@ def test_sam_plugin_rev1(target_win_users, hive_hklm):
     users_key.add_subkey("000003E8", e8_key)
 
     sam_key.add_subkey("Users", users_key)
-    hive_hklm.map_key(sam_key_name, sam_key)
+    hive_hklm.map_key(SAM_KEY_PATH, sam_key)
 
     # Create SYSTEM keys
-    system_key = VirtualKey(hive_hklm, system_key_name)
+    system_key = VirtualKey(hive_hklm, SYSTEM_KEY_PATH)
     data_key = VirtualKey(hive_hklm, "Data", class_name="6d1ae431")
     system_key.add_subkey("Data", data_key)
     gbg_key = VirtualKey(hive_hklm, "GBG", class_name="1ddbd1f5")
@@ -119,7 +121,7 @@ def test_sam_plugin_rev1(target_win_users, hive_hklm):
     system_key.add_subkey("JD", jd_key)
     skew1_key = VirtualKey(hive_hklm, "Skew1", class_name="c42b803c")
     system_key.add_subkey("Skew1", skew1_key)
-    hive_hklm.map_key(system_key_name, system_key)
+    hive_hklm.map_key(SYSTEM_KEY_PATH, system_key)
 
     target_win_users.add_plugin(SamPlugin)
     results = list(target_win_users.sam())
@@ -143,7 +145,7 @@ def test_sam_plugin_rev1(target_win_users, hive_hklm):
 
 @pytest.mark.skipif(not HAVE_CRYPTO, reason="requires pycryptodome")
 def test_sam_plugin_rev2(target_win_users, hive_hklm):
-    sam_key = VirtualKey(hive_hklm, sam_key_name)
+    sam_key = VirtualKey(hive_hklm, SAM_KEY_PATH)
     sam_key.add_value(
         "F",
         bytes.fromhex(
@@ -301,10 +303,10 @@ def test_sam_plugin_rev2(target_win_users, hive_hklm):
     users_key.add_subkey("000003E8", e8_key)
 
     sam_key.add_subkey("Users", users_key)
-    hive_hklm.map_key(sam_key_name, sam_key)
+    hive_hklm.map_key(SAM_KEY_PATH, sam_key)
 
     # Create SYSTEM keys
-    system_key = VirtualKey(hive_hklm, system_key_name)
+    system_key = VirtualKey(hive_hklm, SYSTEM_KEY_PATH)
     data_key = VirtualKey(hive_hklm, "Data", class_name="36f1befb")
     system_key.add_subkey("Data", data_key)
     gbg_key = VirtualKey(hive_hklm, "GBG", class_name="bae89edb")
@@ -313,7 +315,7 @@ def test_sam_plugin_rev2(target_win_users, hive_hklm):
     system_key.add_subkey("JD", jd_key)
     skew1_key = VirtualKey(hive_hklm, "Skew1", class_name="e6f92d89")
     system_key.add_subkey("Skew1", skew1_key)
-    hive_hklm.map_key(system_key_name, system_key)
+    hive_hklm.map_key(SYSTEM_KEY_PATH, system_key)
 
     target_win_users.add_plugin(SamPlugin)
     results = list(target_win_users.sam())
```

2023-01-19 15:59 UTC, JSCU-CNI commented
That's odd, `allow edits by maintainers` is enabled. I've applied your patch to this branch.

2023-01-19 16:12 UTC, Schamper commented
If you fix the unit test this is good to go!

2023-01-19 16:19 UTC, JSCU-CNI commented
I think the unit test breaks because it is using an old version of `flow.record`:

```
FAILED tests/test_plugins_os_windows_sam.py::test_sam_plugin_rev1 - ValueError: unconverted data remains: +00:00
FAILED tests/test_plugins_os_windows_sam.py::test_sam_plugin_rev2 - ValueError: unconverted data remains: +00:00
```

This should work per https://github.com/fox-it/flow.record/pull/37

2023-01-19 21:07 UTC, Schamper commented
Looks like we need to push a new tag for flow.record first then. I'll get that done tomorrow. I already upped the dependency in setup.py.

2023-01-20 15:26 UTC, Schamper approved these changes

2023-01-20 15:37 UTC, merged