Fix windows plugins datetime
fox-it/dissect.target pull request #187
Opened 2023-02-24 17:38 UTC by Zawadidone

Fixes datetime fields of the usb and tasks plugin

2023-02-27 13:04 UTC, Schamper requested changes

2023-02-27 13:04 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/usb.py
> +        ("datetime", "first_instal_date"),
```suggestion
        ("datetime", "first_install_date"),
```

2023-02-27 13:04 UTC, Schamper commented on tests/test_plugins_os_windows_tasks.py
> +    task_file = absolute_path("data/windows-task")
Can you move the test data to `data/plugins/os/windows/tasks/` ?

2023-02-27 13:06 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/usb.py
> +        ("datetime", "first_insert_date"),
Yeah let's do that. Can you also change it throughout the plugin?

2023-02-27 14:51 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/usb.py
> +        ("datetime", "first_insert_date"),
Yes

2023-03-01 10:37 UTC, Schamper approved these changes

2023-03-01 10:38 UTC, merged