Dis 426 add browser download history for each browser plugin
fox-it/dissect.target pull request #191
Opened 2023-03-02 11:20 UTC by Wouter-Jansen

2023-03-02 14:04 UTC, pyrco requested changes

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                # TODO: should implement proper indexing in SQLite at some point
We generally don't leave TODO's in the code, so make it a ticket or fix it ;-)

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                    place: Row = places[place_id]
```suggestion
                    place = places[place_id]
```
We generally don't do type hinting here.

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                    dest_file_info: dict = annotation["downloads/destinationFileURI"]
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                    ended: int = metadata["content"]["endTime"]
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                    ended: int = metadata["content"]["endTime"]
```suggestion
                    ts_end = metadata["content"]["endTime"]
```

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                    download_path: str = dest_file_info["content"]
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                        ts_start=dest_file_info["date_added"],
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                        size=metadata["content"]["fileSize"],
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-02 14:04 UTC, pyrco commented on dissect/target/plugins/browsers/firefox.py
> +                        state=metadata["content"]["state"],
Is this guaranteed to be present? Better make it more robust with a `.get()`

2023-03-03 11:11 UTC, pyrco commented on dissect/target/plugins/browsers/chrome.py
> +        yield from ChromiumMixin.downloads(self, "chrome")
Ehm I mean `super().downloads("chrome") of course.

2023-03-03 11:12 UTC, pyrco commented on dissect/target/plugins/browsers/chromium.py
> +        yield from ChromiumMixin.downloads(self, "chromium")
Ehm I mean `super().downloads("chromium")` of course.

2023-03-03 11:12 UTC, pyrco commented on dissect/target/plugins/browsers/edge.py
> +        yield from ChromiumMixin.downloads(self, "edge")
Ehm I mean `super().downloads("edge")` of course.

2023-03-14 10:03 UTC, pyrco requested changes

2023-03-14 10:03 UTC, pyrco commented
The binary files used for tests should be made in to git-lfs files.

2023-03-16 10:34 UTC, Schamper submitted a review, later dismissed

2023-03-16 10:34 UTC, Schamper commented on .gitattributes
> +tests/data/WebCacheV01.dat.gz filter=lfs diff=lfs merge=lfs -text
Can you move these files to:
```
tests/data/plugins/browsers/iexplore/WebCacheV01.dat.gz
tests/data/plugins/browsers/firefox/places.sqlite
tests/data/plugins/browsers/chrome/History.sqlite
tests/data/plugins/browsers/edge/History.sqlite
tests/data/plugins/browsers/chromium/History.sqlite
```
?

2023-03-17 09:08 UTC, pyrco commented
LGTM

2023-03-17 09:08 UTC, pyrco approved these changes

2023-03-17 09:33 UTC, merged