Improve unix services plugin
fox-it/dissect.target pull request #198
Opened 2023-03-08 10:38 UTC by JSCU-CNI

This PR adds general improvements to the unix services plugin.

- adds support for initd services
- adds unit tests for systemd and initd services
- adds support for multi-line `ExecStart` commands in systemd service config files

2023-03-17 13:10 UTC, Horofic commented
I haven't had time to look at the PR extensively yet. Will pick it up as soon as possible!

2023-03-23 15:26 UTC, pyrco requested changes

2023-03-23 15:26 UTC, pyrco commented on dissect/target/plugins/os/unix/services.py
> +        Resources:
```suggestion
        References:
```

We recently changed the wording. This is the keyword the sphinx doc generator recognizes.

2023-03-27 10:42 UTC, JSCU-CNI commented on dissect/target/plugins/os/unix/services.py
> +    @internal
This could indeed be useful for os specific plugins, e.g. when a plugin only needs to parse systemd or initd, but not both.

2023-03-27 15:38 UTC, pyrco approved these changes

2023-03-28 09:46 UTC, merged