Improve reverse_readlines performance
fox-it/dissect.target pull request #204
Opened 2023-03-16 13:00 UTC by JSCU-CNI

This PR improves `year_rollover_helper` performance by setting the `reverse_readlines` `chunk_size` parameter to 8 MB. This change also makes sure the function does not break when encountering a log line without a valid `re_ts`.

2023-03-16 15:56 UTC, Schamper requested changes

2023-03-20 09:52 UTC, JSCU-CNI commented
Thanks for the suggestions! Implemented in [fa4c04d](https://github.com/fox-it/dissect.target/pull/204/commits/fa4c04d633abe17cbcd3ccb682759f3b70e186f3).

2023-03-24 13:43 UTC, Schamper requested changes
Fixed log formatting + a small suggestion to prevent flooding of warnings

2023-03-24 13:43 UTC, Schamper commented on dissect/target/helpers/utils.py
> +                log.debug(f"Skipping this line: {line}")
```suggestion
                if not warned:
                    log.warning("No timestamp found in one of the lines in %s!", path)
                    warned = True
                log.debug("Skipping line: %s", line)
```

2023-03-24 13:43 UTC, Schamper commented on dissect/target/helpers/utils.py
>      with fsutil.open_decompress(path, "rt") as fh:
```suggestion
    with fsutil.open_decompress(path, "rt") as fh:
        warned = False
```

2023-03-27 10:44 UTC, JSCU-CNI commented
Thanks, implemented in [68f4672](https://github.com/fox-it/dissect.target/pull/204/commits/68f467206fb983b77a5d64d6fdcc87497756344c).

2023-03-29 13:28 UTC, Schamper approved these changes

2023-03-30 07:42 UTC, merged