Add support for unix powershell history
fox-it/dissect.target pull request #212
Opened 2023-03-28 13:48 UTC by JSCU-CNI

This PR adds support for parsing powershell history files on unix systems.

2023-03-31 09:25 UTC, Schamper requested changes

2023-03-31 09:25 UTC, Schamper commented on dissect/target/plugins/os/windows/powershell.py
> +                    source=path.from_windows(str(_path)),
```suggestion
                    source=_path,
```
I believe this should work.

2023-03-31 09:25 UTC, Schamper commented on dissect/target/plugins/os/windows/powershell.py
> +                    mtime=_path.stat().st_mtime,
Maybe nice to improve this and move the `path.stat()` to outside the line iterator, so we only call it once per file.

2023-03-31 09:25 UTC, Schamper commented on dissect/target/plugins/os/windows/powershell.py
Probably a good idea to move this since it now include support for Unix. Perhaps `apps/shell/powershell.py`?

2023-04-06 09:28 UTC, JSCU-CNI commented
Added suggestions in [664536f](https://github.com/fox-it/dissect.target/pull/212/commits/664536fddcd5af4fa8a4b204f380a4f052c177b3).

2023-04-07 11:01 UTC, Schamper commented on dissect/target/plugins/apps/shell/powershell.py
Can you add a `__init__.py` to `dissect/target/plugins/apps/shell`?

2023-04-13 21:33 UTC, Schamper approved these changes

2023-04-13 21:46 UTC, merged