Add documentation testing tooling
fox-it/dissect.target pull request #227
Opened 2023-04-13 09:58 UTC by martinvanhensbergen

Add tox commands to generate API documentation for previewing in browser and automatic checking of broken URLs.

2023-04-24 10:38 UTC, pyrco requested changes

2023-05-01 07:58 UTC, pyrco requested changes

2023-05-01 07:58 UTC, pyrco commented on tox.ini
> +
```suggestion
```
It's the wrong file ;-) Should be added to .gitignore

2023-05-02 07:20 UTC, pyrco approved these changes

2023-05-05 10:48 UTC, Schamper approved these changes

2023-05-11 12:40 UTC, merged