Add dissect.target[yara] as an optional dependency
fox-it/dissect.target pull request #229
Opened 2023-04-18 12:34 UTC by Miauwkeru

2023-04-18 15:00 UTC, pyrco requested changes
The testenv in tox.ini should use the `yara` instead of the `full` extra.

2023-04-18 21:54 UTC, Schamper requested changes
Maybe also nice to add a log message or re-raised `ImportError` that states to install `yara-python` in the YARA plugin file?

2023-04-18 21:54 UTC, Schamper commented on README.md
> +To enable `yara` with `dissect` install `dissect.target[yara]`.
```suggestion
If you wish to use the YARA plugin (`target-query -f yara`), you can install `dissect.target[yara]` instead.

This module is also automatically installed if you install the `dissect` package.
```

2023-04-19 11:16 UTC, Schamper requested changes

2023-04-19 11:16 UTC, Schamper commented on README.md
>  This module is also automatically installed if you install the `dissect` package.
```suggestion
This module is also automatically installed if you install the `dissect` package.

If you wish to use the YARA plugin (`target-query -f yara`), you can install `dissect.target[yara]` to automatically 
install the `yara-python` dependency.
```

I changed my mind :smile: with my previous suggestion it's unclear what "This module" refers to, so better to put this new sentence below.

2023-04-20 07:22 UTC, pyrco approved these changes

2023-05-01 08:32 UTC, Schamper approved these changes

2023-05-01 10:54 UTC, merged