Add plugins for volatile Linux artefacts
fox-it/dissect.target pull request #241
Opened 2023-04-25 15:08 UTC by Horofic

(DIS-1443)

2023-04-26 15:09 UTC, pyrco requested changes

2023-05-04 15:00 UTC, pyrco commented
These files should also be 1 layer lower under `unix/linux/` as `/proc` and `/sys` are linux specific. This probably also has some repercussions on the record names which are now `unix/proc/...`.

2023-05-10 12:48 UTC, pyrco commented on dissect/target/plugins/os/unix/proc.py
> +            socket.owner = self._resolve_uid(socket.user)
```suggestion
            user = self.target.user_details.find(uid=socket.user)
            user_name = user.user.name if user else str(socket.user)
            socket.owner = user_name
```

2023-05-10 12:51 UTC, pyrco commented on dissect/target/plugins/os/unix/proc.py
> +        # uid is 0 we still want to return that
```suggestion
```

2023-06-07 12:16 UTC, Horofic commented on dissect/target/plugins/os/unix/netstat.py
> +    @export(output="none")
Using the `@export` like this causes `target-query` to output a record containing None at the end of the plugin's execution, like so:
`<Target target.tar> None`

Using `@export(output="none")` causes the correct behaviour.

2023-07-04 07:54 UTC, pyrco commented on dissect/target/plugins/os/unix/netstat.py
> +    @export(output="none")
Hmm, that sucks. We should really add a multi-line output type then. I'll add a ticket.

2023-07-04 09:38 UTC, pyrco requested changes

2023-07-04 09:38 UTC, pyrco commented on dissect/target/plugins/os/unix/linux/proc.py
> +    @internal
```suggestion
    @internal
```
As this is not a `Plugin` subclass, this annotation is not needed.

2023-07-04 09:38 UTC, pyrco commented on dissect/target/plugins/os/unix/linux/proc.py
> +    @internal
```suggestion
    @internal
```
As this is not a `Plugin` subclass, this annotation is not needed.

2023-07-04 09:38 UTC, pyrco commented on dissect/target/plugins/os/unix/linux/proc.py
> +    @internal
```suggestion
    @internal
```
As this is not a `Plugin` subclass, this annotation is not needed.

2023-07-07 10:47 UTC, pyrco commented
Could you rebase on or merge in main to see if everything still works? There are quiet some changes.

2023-07-07 10:47 UTC, pyrco reviewed
Could you rebase on or merge in main to see if everything still works? There are quiet some changes.

2023-07-07 12:17 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def _parse_net_sockets(self, protocol: str = "tcp", version: int = None) -> Iterator[NetSocket]:
```suggestion
    def _parse_net_sockets(self, protocol: str = "tcp", version: Optional[int] = None) -> Iterator[NetSocket]:
```

2023-07-07 12:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +            version: the version of the protocol to parse entries from.
```suggestion
            protocol: The protocol in `/proc/net/` to parse entries from.
            version: The version of the protocol.
```

2023-07-07 12:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +            An iterator containg a `NetSocket` dataclass
```suggestion
```
This is redundant IMO because it's just restating the return type.

2023-07-07 12:19 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """
```suggestion
        """Internal function to parse ``/proc/net/unix`` entries."""
```

2023-07-07 12:20 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +            protocol: the protocol in `/proc/net/` to parse entries from.
```suggestion
            protocol: the protocol in ``/proc/net/`` to parse entries from.
```

2023-07-07 12:20 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Yield parsed /proc/net/tcp6 entries."""
```suggestion
        """Yield parsed ``/proc/net/tcp6`` entries."""
```

2023-07-07 12:21 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Yield parsed /proc/net/udp6 entries."""
```suggestion
        """Yield parsed ``/proc/net/udp6`` entries."""
```

2023-07-07 12:27 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Internal function to parse the contents of /proc/[pid]/status."""
```suggestion
        """Internal function to parse the contents of ``/proc/[pid]/status``."""
```

2023-07-07 12:27 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Internal function to parse the contents of /proc/[pid]/stat."""
```suggestion
        """Internal function to parse the contents of ``/proc/[pid]/stat``."""
```

2023-07-07 12:27 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        status = self.get("status").open()
Why not open in text mode if you're going to be `.decode()`'ing everything anyway?

2023-07-07 12:28 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def _parse_proc_status_entry(self) -> dict:
```suggestion
    def _parse_proc_status_entry(self) -> dict[str, str]:
```

2023-07-07 12:28 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        status = self.get("stat").open().readline()
Same here, why not open in text mode?

2023-07-07 12:28 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def _parse_proc_stat_entry(self) -> dict:
```suggestion
    def _parse_proc_stat_entry(self) -> dict[str, Union[str, int]]:
```

2023-07-07 12:28 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Internal function to parse entries in /proc/[pid]/environ"""
```suggestion
        """Internal function to parse entries in ``/proc/[pid]/environ``."""
```

2023-07-07 12:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +                # Covention tells us that variable names and values are split on '='
```suggestion
                # Convention tells us that variable names and values are split on '='
```

2023-07-07 12:38 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Returns the `now()` timestamp of the system at the moment of acquisition."""
```suggestion
        """Returns the ``now()`` timestamp of the system at the moment of acquisition."""
```

2023-07-07 12:42 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """
```suggestion
        """Yields ``/proc/<pid>`` filesystems entries for every process id (pid) found in procfs."""
```
You also use `<pid>` here but `[pid]` in some of the docstrings above.

2023-07-07 12:43 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        self._set_inode_pid_map()
You could use a `@cached_property` to do this more cleanly.

2023-07-07 12:43 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def process(self, pid) -> ProcProcess:
```suggestion
    def process(self, pid: int) -> ProcProcess:
```
I guess?

2023-07-07 12:44 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/processes.py
> +        Each /proc/[pid] subdirectory contains various pseudo-files.
```suggestion
        """This plugin yields the processes available in ``/proc`` and the stats associated with them.

        There is a numerical subdirectory for each running process; the subdirectory is named by the process ID.
        Each ``/proc/[pid]`` subdirectory contains various pseudo-files.
```
Also note that you use `[pid]` here again.

2023-07-07 12:45 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def check_compatible(self) -> bool:
```suggestion
    def check_compatible(self) -> None:
```

2023-07-07 12:45 UTC, Schamper commented on dissect/target/plugins/os/unix/netstat.py
> +    def netstat(self) -> None:
```suggestion
    def netstat(self) -> Iterator[str]:
```

2023-07-07 12:46 UTC, pyrco submitted a review, later dismissed

2023-07-07 12:47 UTC, Schamper commented on dissect/target/plugins/os/unix/sockets.py
> +            """This plugin yields the packet sockets and available stats associated with them.
The docstring is a line too high.

2023-07-07 12:48 UTC, Schamper commented on dissect/target/plugins/os/unix/sockets.py
> +    def _generate_unix_socket_record(self, data: dataclass) -> UnixSocketRecord:
Can't the type hint for `data` be more specific?

2023-07-07 12:48 UTC, Schamper commented on dissect/target/plugins/os/unix/sockets.py
> +    def _generate_packet_socket_record(self, data: dataclass) -> PacketSocketRecord:
Can't the type hint for `data` be more specific?

2023-07-07 12:48 UTC, Schamper commented on dissect/target/plugins/os/unix/sockets.py
> +    def _generate_net_socket_record(self, data: dataclass) -> NetSocketRecord:
Can't the type hint for `data` be more specific?

2023-08-21 09:50 UTC, Schamper requested changes
I also see you've changed `uid` to `User ID (uid)` with capitalization but left things like `parent process id (ppid)` lowercased. Can you choose one and make the rest consistent?

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +                socket.rem_address.split(":")[1],
I see there's a `local_ip` and `remote_ip` field in the dataclass but you don't fill them?

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +            field_names = fields(cls)
```suggestion
        # So we use the fields(NetSocket) to dynamically fill the NetSocket dataclass.
        field_names = fields(cls)
        for idx, value in enumerate(line.split()):
```

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
>          for idx, value in enumerate(line.split()):
Would `socket = cls(*line.split())` also work? Same for the other places where you do something like this btw.

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
>      owner: str = field(default=None)  # resolved owner from user (uid) field
If you're only specifying the default value, would this not work as well (and be a little cleaner)?

```suggestion
    owner: Optional[str] = None # resolved owner from user (uid) field
```

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        # status = self.entry("stat").open().readline()
```suggestion
```

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +                variable, contents = line.decode().split("=", maxsplit=1)
Why not open in text mode too?

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        return self.entry.joinpath(path)
```suggestion
    def get(self, path: pathlib.Path) -> pathlib.Path:
        """Returns a ``Path`` relative to this process."""
        return self.entry.joinpath(path)
```
I don't think there's any specific reason to note that it's a `TargetPath`, so just use the more generic `Path`.

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Returns the parentprocess id (pid) associated to this process."""
Is this correct? Wouldn't parent process be `ppid`?

2023-08-21 09:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        """Yields ``/proc/[pid]`` filesystems entries for every process id (pid) found in procfs."""
Why not use `TargetPath` here too?

2023-09-06 13:04 UTC, Schamper requested changes

2023-09-06 13:04 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    protocol_string: Optional[str] = "unix"
```suggestion
    protocol_string: str = "unix"
```

2023-09-06 13:04 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    protocol_string: Optional[str] = "packet"
```suggestion
    protocol_string: str = "packet"
```

2023-09-06 13:04 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +def parse_ip(addr: Union[str, int], version: int = 4) -> IPv6Address | IPv4Address:
```suggestion
def parse_ip(addr: Union[str, int], version: int = 4) -> Union[IPv4Address, IPv4Address]:
```

2023-09-06 13:04 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +        lines = environ.read().split("\x00")
```suggestion
        lines = self.get("environ").read_text().split("\x00")
```

2023-09-11 22:28 UTC, Schamper requested changes

2023-09-11 22:28 UTC, Schamper commented on tests/data/proc/net/packet
Can you move all these files to `tests/data/unix/linux/proc`?

2023-09-11 22:28 UTC, Schamper commented on tests/test_unix_proc.py
Can you rename this file `test_plugins_os_unix_linux_proc.py`?

2023-09-11 22:28 UTC, Schamper commented on dissect/target/plugins/os/unix/sockets.py
Should this file not be in `os/unix/linux/sockets.py`?

2023-09-11 22:28 UTC, Schamper commented on dissect/target/plugins/os/unix/netstat.py
Should this file not be in `os/unix/linux/netstat.py`?

2023-09-11 22:28 UTC, Schamper commented on tests/test_unix_proc_sockets.py
Can you rename this file `test_plugins_os_unix_linux_sockets.py`? If the comment about the location of `sockets.py` holds true.

2023-09-13 09:18 UTC, Schamper requested changes

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/cmdline.py
> +    def cmdline(self) -> Iterator[TargetRecordDescriptor]:
```suggestion
    def cmdline(self) -> Iterator[CmdlineRecord]:
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/cmdline.py
> +            raise UnsupportedPluginError("No /proc directory found")
```suggestion
        self.target.proc
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/cmdline.py
> +        """
We have a 120 character line limit, perhaps make a little bit more use of that.

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/environ.py
> +        execve(2).
```suggestion
        """Return the initial environment for all processes when they were started via execve(2).
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    ref: int  # the number of users of the socket.
```suggestion
    num: str  # the kernel table slot number
    ref: int  # the number of users of the socket
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    flags: str  # the internal kernel flags holding the status of the socket.
```suggestion
    flags: str  # the internal kernel flags holding the status of the socket
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    state: int  # the internal state of the socket.
```suggestion
    state: int  # the internal state of the socket
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    # and are shown with a Path that commences with the character '@'.
```suggestion
    # and are shown with a path that commences with the character '@'
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    ref: int  # the number of processes using this socket.
```suggestion
    ref: int  # the number of processes using this socket
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    user: int  # uid from the owner of the socket.
```suggestion
    iface: int  # network interface index
    r: int  # number of bytes that have been received by the socket and are waiting to be processed
    rmem: int  # receive window memory
    user: int  # uid from the owner of the socket
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    # Values parsed from raw values listed above.
```suggestion
    # Values parsed from raw values listed above
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def inode_map(self) -> defaultdict:
```suggestion
    def inode_map(self) -> dict[int, list[ProcProcess]]:
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/proc.py
> +    def inode_to_pids(self, inode: int) -> list:
```suggestion
    def inode_to_pids(self, inode: int) -> list[ProcProcess]:
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/processes.py
> +    def processes(self) -> Iterator[TargetRecordDescriptor]:
```suggestion
    def processes(self) -> Iterator[ProcProcessRecord]:
```

2023-09-13 09:18 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/processes.py
> +        """This plugin yields the processes available in ``/proc`` and the stats associated with them.
```suggestion
        """Return the processes available in ``/proc`` and the stats associated with them.
```

2023-09-13 11:07 UTC, Schamper approved these changes

2023-09-13 11:09 UTC, Schamper requested changes

2023-09-13 11:09 UTC, Schamper commented on tests/conftest.py
> +def fs_unix_proc(fs_unix):
```suggestion
def fs_linux_proc(fs_unix):
```

2023-09-13 11:09 UTC, Schamper commented on tests/conftest.py
> +def fs_unix_proc(fs_unix):
And maybe based on `fs_linux`?

2023-09-13 11:09 UTC, Schamper commented on tests/conftest.py
> +def fs_unix_proc_sockets(fs_unix_proc):
```suggestion
def fs_linux_proc_sockets(fs_linux_proc):
```

2023-09-13 11:09 UTC, Schamper commented on tests/conftest.py
> +    profile2_key.add_value(
This has been re-introduced.

2023-09-13 13:00 UTC, Schamper requested changes

2023-09-13 13:00 UTC, Schamper commented on tests/conftest.py
> +    profile2_key.add_value(
Fix your black

2023-09-13 13:41 UTC, Schamper requested changes

2023-09-13 13:41 UTC, Schamper commented on tests/conftest.py
> +    fs.map_file_fh("/proc/net/tcp", open(absolute_path("data/unix/linux/proc/net/tcp"), "rb"))
Can you make this a loop over some filenames?

2023-09-14 10:31 UTC, Schamper requested changes

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_packet_socket_record(packetsocket)
```suggestion
        yield from map(self._generate_packet_socket_record, self.sockets.packet())
```

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_unix_socket_record(unixsocket)
```suggestion
        yield from map(self._generate_unix_socket_record, self.sockets.unix())
```

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_packet_socket_record(packetsocket)
Also missing a unit test for this one.

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_net_socket_record(netsocket)
```suggestion
        yield from map(self._generate_net_socket_record, chain(self.sockets.raw(), self.sockets.raw6()))
```

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_net_socket_record(netsocket)
```suggestion
        yield from map(self._generate_net_socket_record, chain(self.sockets.udp(), self.sockets.udp6()))
```

2023-09-14 10:31 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/sockets.py
> +            yield self._generate_net_socket_record(netsocket)
```suggestion
        yield from map(self._generate_net_socket_record, chain(self.sockets.tcp(), self.sockets.tcp6()))
```

2023-09-14 14:28 UTC, Schamper approved these changes

2023-09-14 14:29 UTC, merged