Return correct amcache_install records
fox-it/dissect.target pull request #265
Opened 2023-06-02 09:32 UTC by Miauwkeru

Returns the actual amcache_create entry

(DIS-1998)

2023-06-02 13:19 UTC, cecinestpasunepipe approved these changes
LGTM

2023-06-06 09:03 UTC, pyrco requested changes

2023-06-06 09:03 UTC, pyrco commented on dissect/target/plugins/os/windows/log/amcache.py
>              created = []
```suggestion
            arp_created = []
            file_created = []
```

Maybe change this also while we're at it, makes it a bit more readable.

2023-06-07 09:48 UTC, cecinestpasunepipe approved these changes
LGTM

2023-06-08 07:18 UTC, merged