Add exclusions function to Windows Defender plugin
fox-it/dissect.target pull request #301
Opened 2023-06-30 18:55 UTC by MaxGroot

2023-06-30 21:21 UTC, Schamper requested changes

2023-06-30 21:21 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +    [("datetime", "regf_mtime"), ("string", "type"), ("string", "value")],
```suggestion
    [
        ("datetime", "regf_mtime"),
        ("string", "type"),
        ("string", "value"),
    ],
```

2023-06-30 21:21 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +    def exclusions(self) -> Generator[Record, None, None]:
```suggestion
    def exclusions(self) -> Iterator[DefenderExclusionRecord]:
```

2023-06-30 21:21 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +                        regf_mtime=exclusion_type_last_modified, type=exclusion_type, value=exclusion_value
```suggestion
                        regf_mtime=exclusion_type_subkey.timestamp,
                        type=exclusion_type,
                        value=exclusion_value,
                        _target=self.target,
```

2023-06-30 21:21 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +                    exclusion_type_last_modified = exclusion_type_subkey.timestamp
```suggestion
```

2023-07-01 10:40 UTC, Schamper requested changes

2023-07-01 10:40 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +    def exclusions(self) -> Generator[Record]:
```suggestion
    def exclusions(self) -> Iterator[Record]:
```

2023-07-01 11:15 UTC, Schamper requested changes

2023-07-01 11:15 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +    def exclusions(self) -> Iterator[Record]:
```suggestion
    def exclusions(self) -> Iterator[DefenderExclusionRecord]:
```

2023-07-01 11:21 UTC, Schamper requested changes

2023-07-01 11:21 UTC, Schamper commented on tests/test_plugins_os_windows_defender.py
> +    target_win.registry.map_hive("HKEY_LOCAL_MACHINE", hive_hklm)
```suggestion
def test_defender_exclusions(target_win, hive_hklm):
    # https://learn.microsoft.com/en-us/exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2019
    exclusions_example = {
        "Extensions": [".config", ".log", ".cfg"],
        "Processes": ["UmService.exe", "UmWorkerProcess.exe"],
        "Paths": ["C:\\System32\\Cluster\\"],
        "IpAddresses": [],
        "TemporaryPaths": [],
    }

    # Recreate the 'Exclusions' registry key based on the example dict
    exclusions_key = VirtualKey(hive_hklm, "Software\\Microsoft\\Windows Defender\\Exclusions")
    for exclusion_type, exclusions in exclusions_example.items():
        exclusion_type_key = VirtualKey(hive_hklm, exclusions_key.path + f"\\{exclusion_type}")
        for exclusion in exclusions:
            exclusion_type_key.add_value(exclusion, 0)
        exclusions_key.add_subkey(exclusion_type, exclusion_type_key)

```
If you add the `hive_hklm` fixture, you get the one that's already mapped into the `target_win` fixture.

2023-07-01 11:21 UTC, Schamper commented on tests/test_plugins_os_windows_defender.py
> +    target_win.registry.map_hive("HKEY_LOCAL_MACHINE", hive_hklm)
Also, we started adding type hints to the test functions, could you add those?

2023-07-03 08:03 UTC, Schamper requested changes

2023-07-03 08:03 UTC, Schamper commented on dissect/target/plugins/os/windows/defender.py
> +        """Yield Microsoft Defender exclusions from the Registry"""
```suggestion
        """Yield Microsoft Defender exclusions from the Registry."""
```

2023-07-05 12:02 UTC, Schamper submitted a review, later dismissed

2023-07-05 12:11 UTC, pyrco commented on dissect/target/plugins/os/windows/defender.py
> +                self.target.has_function("registry"),
Not just the registry, but the `DEFENDER_EXCLUSION_KEY` should also exist

2023-07-05 12:39 UTC, pyrco approved these changes

2023-07-05 12:57 UTC, merged