Add Windows support for the ssh plugin
fox-it/dissect.target pull request #306
Opened 2023-07-10 09:31 UTC by Miauwkeru

- Move os/unix/ssh.py to apps/ssh/openssh.py
- Create tests for windows version of openssh
- Replace C:\\ with sysvol in output for some tests
- Abstract looking for sshd directory
- rename record descriptor names

(DIS-1854)

2023-07-10 13:06 UTC, Schamper requested changes

2023-07-10 13:06 UTC, Schamper commented on dissect/target/plugins/apps/ssh/openssh.py
Can you add a `__init__.py` to the `ssh` directory?

2023-07-17 11:00 UTC, pyrco commented on dissect/target/plugins/apps/ssh/openssh.py
> +    def _sshd_directory(self) -> TargetPath:
Would it be useful to make this an `@property`? And then also possibly caching it by saving it to some instance variable.

2023-07-17 15:05 UTC, cecinestpasunepipe requested changes

2023-07-18 07:50 UTC, pyrco commented on dissect/target/plugins/apps/ssh/openssh.py
> +    def _sshd_directory(self) -> TargetPath:
Even better  :laughing:

2023-07-18 07:54 UTC, pyrco commented on dissect/target/plugins/apps/ssh/openssh.py
> +        return len(list(self.target.users())) > 0 or self.sshd_directory.exists()
You want to check for both client and server dirs, but technically the users check doesn't really do the former..

2023-07-18 11:25 UTC, cecinestpasunepipe commented on dissect/target/plugins/apps/ssh/openssh.py
> +        if (target_path := self.target.fs.path("/sysvol/ProgramData/ssh")).exists():
Ok, nice.

2023-07-18 13:13 UTC, cecinestpasunepipe requested changes

2023-07-18 13:13 UTC, cecinestpasunepipe commented on dissect/target/plugins/apps/ssh/openssh.py
>      def authorized_keys(self) -> Iterator[AuthorizedKeysRecord]:
Can you still update the docstrings? The output now still says it is UNIX-only.

2023-07-19 10:11 UTC, cecinestpasunepipe approved these changes

2023-07-19 10:12 UTC, cecinestpasunepipe commented
LGTM,

Still please don't forget to address @pyrco 's change requests. But regarding my suggestions, I am OK with it.

2023-07-19 13:45 UTC, pyrco approved these changes

2023-07-19 14:21 UTC, merged