Register squashfs filesystem
fox-it/dissect.target pull request #324
Opened 2023-07-19 15:49 UTC by JSCU-CNI

This PR registers squashfs as a filesystem for dissect.target.

2023-07-20 09:26 UTC, pyrco requested changes
Thanks for this missing squashfs piece!

In general it looks good. However `is_dir()`, `if_file()` and `stat()`  these days have an extra `follow_symlinks` parameter (to ensure support for Python >= 3.11.4). Could you implement those as well? The implementations in `extfs.py` can be used as a good example.

2023-07-20 11:30 UTC, JSCU-CNI commented
Thanks for the suggestion. [Added](https://github.com/fox-it/dissect.target/pull/324/commits/329dfcfb3f21b30b91201ec5144a83ecf0790b15) updated `is_dir()`, `is_file()`, `is_symlink()` and `stat()` functions. Also removed unnecessary `_resolve()` definition as it's identical to the inherited `FilesystemEntry` class and tweaked the returned `st_info` inside `stat()`.

2023-07-20 19:42 UTC, Schamper requested changes

2023-07-20 19:42 UTC, Schamper commented on dissect/target/filesystems/squashfs.py
> +        return sb.s_magic == c_squashfs.c_squashfs.SQUASHFS_MAGIC
```suggestion
        return int.from_bytes(fh.read(4), "little") == c_squashfs.c_squashfs.SQUASHFS_MAGIC
```

2023-07-20 19:42 UTC, Schamper commented on dissect/target/filesystems/squashfs.py
> +                0,  # nlink
```suggestion
                getattr(node.header, "nlink", 0),
```
?

2023-07-20 19:42 UTC, Schamper commented on dissect/target/filesystems/squashfs.py
> +
```suggestion
```

2023-07-24 14:56 UTC, pyrco approved these changes

2023-07-24 19:09 UTC, Schamper approved these changes

2023-07-24 19:27 UTC, merged