IIS only add logfiles if it exists in the xml
fox-it/dissect.target pull request #344
Opened 2023-08-03 12:00 UTC by Miauwkeru

- Add tests for different logfile notation in webservers
- Add iis log directory if it is definedi

(DIS-2116)

2023-08-03 23:26 UTC, Schamper requested changes

2023-08-03 23:26 UTC, Schamper commented on tests/test_plugins_apps_webservers_iis.py
> +def test_iis_plugin_iis_format(
Can you add type hints?

2023-08-04 08:51 UTC, Poeloe commented on tests/data/webservers/iis/iis-applicationHost-w3c-alternative.config
Maybe make the log filename a bit more descriptive, such that it is more clear what is different.

I would suggest: `iis-applicationHost-w3c-additional-logFile-element.config`

2023-08-04 09:12 UTC, Poeloe commented on tests/data/webservers/iis/iis-applicationHost-w3c-undefined-logfile-directory.config
Would suggest : iis-applicationHost-w3c-logFile-without-directory-attr.config

2023-08-04 09:25 UTC, Poeloe approved these changes

2023-08-04 19:08 UTC, Schamper approved these changes

2023-08-07 06:52 UTC, merged