allow Default/None-OS to access plugins
fox-it/dissect.target pull request #346
Opened 2023-08-04 13:36 UTC by cecinestpasunepipe

(DIS-2138)

2023-08-04 13:45 UTC, Poeloe requested changes
Please include a test, since we did not notice this bug with our tests

2023-08-04 15:15 UTC, Schamper commented on tests/test_plugin.py
> +def test_find_plugin_function_default(target_default):
Can you add type hints to the test?

2023-08-04 16:10 UTC, Poeloe approved these changes
LGTM!

2023-08-07 15:21 UTC, Schamper approved these changes

2023-08-07 15:23 UTC, merged