Add OSX ips function
fox-it/dissect.target pull request #348
Opened 2023-08-04 15:29 UTC by Zawadidone

2023-08-04 19:02 UTC, Schamper requested changes

2023-08-04 19:02 UTC, Schamper commented on dissect/target/plugins/os/unix/bsd/osx/_os.py
> +                    ips.add(ip_address)
```suggestion
                ips.update(addresses.get("Addresses", []))
```

2023-08-04 21:09 UTC, Schamper requested changes

2023-08-04 21:09 UTC, Schamper commented on dissect/target/plugins/os/unix/bsd/osx/_os.py
> +                ips.add(lease.get("IPAddress"))
```suggestion
                if ip := lease.get("IPAddress"):
                    ips.add(ip)
```

2023-08-04 21:09 UTC, Schamper commented on dissect/target/plugins/os/unix/bsd/osx/_os.py
> +        return list(filter(None, ips))
```suggestion
        return list(ips)
```

2023-08-05 21:19 UTC, Schamper approved these changes

2023-08-05 21:30 UTC, merged

2023-08-05 21:41 UTC, Zawadidone commented
Thanks!