Generic config_tree implementation
fox-it/dissect.target pull request #354
Opened 2023-08-11 14:05 UTC by Miauwkeru

- Add basic unix registry parts
- Create Config parser
- simplify get logic
- Detect configuration files
- add todo
- Add a generic space delimited config parser
- Update hacked together "registry"

2023-08-14 11:26 UTC, cecinestpasunepipe requested changes

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +
```suggestion
KNOWN_FILES: dict[str, LinuxConfigurationParser] = {
    "ulogd.conf": Ini,
}
```

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +
I think there are 2 base cases: extensions and well known files.

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +        parser = CONFIG_MAP.get(extension, Unknown)(collapse)
```suggestion
        parser = CONFIG_MAP.get(extension, KNOWN_FILES.get(entry.name, Unknown))(collapse)
```

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +                output.write(bytes(key, "utf8"))
```suggestion
                output.write(bytes(key, "utf-8"))
```

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +    def iterdir(self):
return type?

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +    def open(self):
return type?

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +    def scandir(self):
return type?

2023-08-14 11:26 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config_tree.py
> +    def _write_value_mapping(self, output: io.BytesIO, data: dict[str, Any]):
return type?

2023-08-16 15:14 UTC, cecinestpasunepipe requested changes

2023-08-16 15:14 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/config.py
> +class Unknown(LinuxConfigurationParser):
Is this really unknown? It seems to me this is the standard Unix config style. I would recommend to name this Default instead.

2023-08-17 11:42 UTC, cecinestpasunepipe approved these changes

2023-08-17 11:43 UTC, merged

2023-08-18 15:01 UTC, Schamper reviewed
I also wonder if aligning closer with the Windows registry implementation would make more sense, instead of the filesystem implementation.