Update VelociraptorLoader based on version 0.7.0
fox-it/dissect.target pull request #358
Opened 2023-08-14 20:48 UTC by Zawadidone

Add new accessors

2023-08-14 20:49 UTC, Zawadidone commented
The volumes and paths are mapped correctly but the NTFS filesystem is not correctly parsed. I will try to find the bug that causes this.

```
Traceback (most recent call last):
  File "/dissect.target/dissect/target/target.py", line 404, in _load
    ldr.map(target)
  File "/dissect.target/dissect/target/loaders/velociraptor.py", line 75, in map
    map_dirs(
  File "/dissect.target/dissect/target/loaders/dir.py", line 54, in map_dirs
    loaderutil.add_virtual_ntfs_filesystem(target, dfs, **kwargs)
  File "/dissect.target/dissect/target/helpers/loaderutil.py", line 36, in add_virtual_ntfs_filesystem
    ntfs = NtfsFilesystem(boot=fh_boot, mft=fh_mft, usnjrnl=fh_usnjrnl, sds=fh_sds)
  File "/dissect.target/dissect/target/filesystems/ntfs.py", line 36, in __init__
    self.ntfs = NTFS(fh, boot=boot, mft=mft, usnjrnl=usnjrnl, sds=sds)
  File "/dissect.target/.tox/py3/lib/python3.10/site-packages/dissect/ntfs/ntfs.py", line 50, in __init__
    self.boot_sector = c_ntfs.BOOT_SECTOR(boot_fh)
  File "/dissect.target/.tox/py3/lib/python3.10/site-packages/dissect/cstruct/types/base.py", line 24, in __call__
    return self.read(*args, **kwargs)
  File "/dissect.target/.tox/py3/lib/python3.10/site-packages/dissect/cstruct/types/base.py", line 73, in read
    return self._read(obj)
  File "<compiled _BOOT_SECTOR>", line 15, in _read
EOFError
```

2023-08-15 09:47 UTC, Schamper commented
Looks like it tries to open the `$Boot` file (which I'm not sure if Velociraptor collects?). It seems to exist (otherwise `boot_fh` would be `None`) but it's too small to actually contain a boot sector. If this is inherently a Velociraptor problem, we could put a try/except in the NTFS code that reads the boot sector.

2023-08-15 11:40 UTC, Zawadidone commented
It does collect the file but with a file size of `0` which normally is not a problem, but the bug (https://github.com/Velocidex/velociraptor/issues/2892) has reintroduced itself for the second time. I don't understand the NTFS code good enough to determine if a try/except improves the loader, but if does could you add it to the PR or https://github.com/fox-it/dissect.ntfs.

I expect that the bug will be fixed in the next release of Velociraptor. I have changed the PR to ready for review because the loader functions correctly.

2023-08-15 11:59 UTC, Schamper commented
A cleaner fix might be to check for `st_size > 0` in here: https://github.com/fox-it/dissect.target/blob/main/dissect/target/helpers/loaderutil.py#L44-L48. All of the files that need to be opened should be larger anyway.

2023-08-15 14:29 UTC, Schamper requested changes

2023-08-15 14:29 UTC, Schamper commented on tests/test_loaders_velociraptor.py
> +def test_velociraptor_loader_windows_ntfs(paths: List[str], mock_target: Target, tmp_path: Path) -> None:
```suggestion
def test_velociraptor_loader_windows_ntfs(paths: list[str], mock_target: Target, tmp_path: Path) -> None:
```

2023-08-15 14:29 UTC, Schamper commented on tests/test_loaders_velociraptor.py
> +def test_dir_loader_unix(paths: List[str], mock_target: Target, tmp_path: Path) -> None:
```suggestion
def test_dir_loader_unix(paths: list[str], mock_target: Target, tmp_path: Path) -> None:
```
Some cleanup of old style type hints.

2023-08-15 14:29 UTC, Schamper commented on dissect/target/helpers/loaderutil.py
> +                pass
```suggestion
            entry = fs.get(path)
            if entry.stat().st_size > 0:
                return path.open()
            else:
                log.warning("File is empty and will be skipped: %s", path)
```

2023-08-15 14:29 UTC, Schamper commented on dissect/target/helpers/loaderutil.py
> +def _try_open(fs, path) -> None:
```suggestion
def _try_open(fs: Filesystem, path: str) -> None:
```
And add the import for `from dissect.target.filesystem import Filesystem`

2023-08-15 15:23 UTC, Schamper requested changes

2023-08-15 15:23 UTC, Schamper commented on dissect/target/helpers/loaderutil.py
>  from typing import Optional, Tuple, Union
While you're here, could you replace the type hint that currently uses `Tuple` with `tuple`? Thanks!

2023-08-18 14:45 UTC, Schamper requested changes

2023-08-18 14:45 UTC, Schamper commented on dissect/target/helpers/loaderutil.py
> +def _try_open(fs: Filesystem, path: str) -> None:
```suggestion
def _try_open(fs: Filesystem, path: str) -> BinaryIO:
```

2023-08-18 15:16 UTC, Schamper requested changes
Small nitpicky comment, good to go otherwise.

2023-08-18 15:16 UTC, Schamper commented on dissect/target/helpers/loaderutil.py
> +                pass
```suggestion
```

2023-08-18 15:39 UTC, Schamper approved these changes

2023-08-18 15:50 UTC, merged