Update tasks_xml.py
fox-it/dissect.target pull request #401
Opened 2023-09-18 12:24 UTC by 0x49736b

If Principals/Principal/DisplayName is empty, use the filename as the display_name.

I noticed that the field "Principals/Principal/DisplayName" is not used a lot, resulting in the Display Name being null for most of the records.

Instead, let's use the filename as Display Name (Like in the Task Scheduler GUI)

2023-09-18 12:37 UTC, Schamper requested changes

2023-09-18 12:37 UTC, Schamper commented on dissect/target/plugins/os/windows/task_helpers/tasks_xml.py
> +            self.display_name = str(task_path)[str(task_path).rfind("/")+1:]
```suggestion
        self.display_name = self.get_element("Principals/Principal/DisplayName") or task_path.name
```
I believe this achieves the same result.

2023-09-18 12:49 UTC, 0x49736b commented
@DissectBot agree

2023-09-18 13:51 UTC, Schamper commented
Could you adjust the unit tests with the newly filled in field?

2023-09-19 09:49 UTC, 0x49736b commented
> Could you adjust the unit tests with the newly filled in field?

@Schamper , done here https://github.com/fox-it/dissect.target/pull/401/commits/e75a335467853d7643c795f62f5ccc5b307611fe

2023-09-20 17:09 UTC, Schamper requested changes

2023-09-20 17:09 UTC, Schamper commented on tests/test_plugins_os_windows_tasks.py
> +    assert xml_task.display_name is "test_xml.xml"
```suggestion
    assert xml_task.display_name == "test_xml.xml"
```
Usually you only use a `is` comparison on things like `None` or class types. Any other type of comparison should be done with `==`.

2023-09-21 08:53 UTC, Schamper approved these changes

2023-09-21 08:54 UTC, merged