Fix small bugs in Android OS Plugin
fox-it/dissect.target pull request #415
Opened 2023-10-14 20:54 UTC by MaxGroot

* Fix incorrect accessing of path on the target's filesystem
* Fix exceptions when build property doesn't contain a security patch
* Add small test

2023-10-15 14:24 UTC, Schamper requested changes

2023-10-15 14:24 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/android/_os.py
> +            full_version += f" {release_version}"
```suggestion
        if release_version := self.props.props.get("ro.build.version.release"):
            full_version += f" {release_version}"
```

2023-10-15 14:24 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/android/_os.py
> +            full_version += f" ({security_patch_version})"
```suggestion
        if security_patch_version := self.props.props.get("ro.build.version.security_patch"):
            full_version += f" ({security_patch_version})"
```

2023-10-15 14:24 UTC, Schamper commented on tests/conftest.py
> +    mock_target = next(make_mock_target())
```suggestion
    mock_target = next(make_mock_target())
    mock_target._os_plugin = AndroidPlugin
```

2023-10-15 14:24 UTC, Schamper commented on tests/conftest.py
> +    mock_filesystem.map_file("/build.prop", absolute_path("data/plugins/os/unix/linux/android/build.prop"))
Could you split this into a separate fixture called `fs_android`?

2023-10-15 14:24 UTC, Schamper commented on tests/test_plugins_os_unix_linux_android.py
> +def test_unix_linux_android_os(target_android):
```suggestion
def test_android_os(target_android: Target) -> None:
```

2023-10-16 06:57 UTC, MaxGroot commented
While testing on a different Android system I found some other inconsistencies, I'll make sure to add fixes for those in this PR as well. In the meantime I'm converting it back to draft.

2023-10-16 08:53 UTC, Schamper requested changes

2023-10-16 08:53 UTC, Schamper commented on tests/conftest.py
> +def target_android(fs_android) -> Target:
```suggestion
def target_android(fs_android: VirtualFilesystem) -> Target:
```

2023-10-16 08:53 UTC, Schamper commented on tests/test_plugins_os_unix_linux_android.py
> +def test_android_os(target_android) -> None:
```suggestion
def test_android_os(target_android: Target) -> None:
```

2023-11-04 17:55 UTC, Schamper approved these changes

2023-11-04 23:25 UTC, merged