Add target-shell's ls command options
fox-it/dissect.target pull request #431
Opened 2023-11-01 07:36 UTC by mnrkbys

Added following target-shell's ls command options:
```
  -u                    Use time of last access.
  -c                    Use time when file status was last changed.
  -R                    Recursively list subdirectories encountered.
```

2023-11-01 14:42 UTC, pyrco commented
Thanks for these useful additions! Once the CLA accepted, we will plan reviewing this PR.

2023-11-01 17:35 UTC, mnrkbys commented
@DissectBot agree

2023-11-07 23:48 UTC, Schamper requested changes

2023-11-07 23:48 UTC, Schamper commented on dissect/target/tools/shell.py
> +    def _recursive_ls(self, args: argparse.Namespace, dir_name: fsutil.TargetPath, stdout: TextIO) -> Optional[bool]:
There's currently quite a bit of code duplication between this and `cmd_ls`. Do you think you could re-use more? I.e. let `_recursive_ls` be the main body (perhaps rename it something like `_print_ls`?), and do the print on line 540 conditionally if the function is being called recursively (through an additional argument).

2023-11-07 23:48 UTC, Schamper commented on dissect/target/tools/shell.py
> +                utc_time = datetime.datetime.utcfromtimestamp(stat.st_mtime).isoformat()
```suggestion
            show_time = stat.st_mtime
            if args.use_ctime:
                show_time = stat.st_ctime
            elif args.use_atime:
                show_time = stat.st_atime
            utc_time = datetime.datetime.utcfromtimestamp(show_time).isoformat()
```

2023-11-07 23:48 UTC, Schamper commented on dissect/target/tools/shell.py
> +    @arg("-u", action="store_true", dest="use_atime", help="Show time of last access.")
```suggestion
    @arg("-R", "--recursive", action="store_true", help="recursively list subdirectories encountered")
    @arg("-c", action="store_true", dest="use_ctime", help="show time when file status was last changed")
    @arg("-u", action="store_true", dest="use_atime", help="show time of last access")
```
The lowercasing is mostly for consistency with an average bash shell.

2023-11-07 23:48 UTC, Schamper commented on dissect/target/tools/shell.py
> +            print("Cannot specify -c and -u at the same time.")
```suggestion
            print("can't specify -c and -u at the same time")
```
The lowercasing is mostly for consistency with an average bash shell.

2023-11-07 23:48 UTC, Schamper commented on dissect/target/tools/shell.py
> +        print(f"\n{str(path)}:")
```suggestion
        print(f"\n{str(path)}:", file=stdout)
```

2024-03-18 05:28 UTC, mnrkbys commented
I was very busy and could not fix it for a while.
Now, I have modified the code according to the comments.

2024-03-18 15:07 UTC, Schamper requested changes
Thanks! Just some small stylistic suggestions. Could you also rebase on the latest main branch?

2024-03-18 15:07 UTC, Schamper commented on dissect/target/tools/shell.py
> +                self._print_ls(args, dir_name, dir_depth+1, stdout)
```suggestion
                self.print_extensive_file_stat(args=args, stdout=stdout, target_path=target_path, name=name)
                if target_path.is_dir():
                    subdirs.append(target_path)

        if args.recursive and subdirs:
            for subdir in subdirs:
                self._print_ls(args, subdir, depth + 1, stdout)
```

2024-03-18 15:07 UTC, Schamper commented on dissect/target/tools/shell.py
> +                    dir_list.append(target_path)
```suggestion
                    subdirs.append(target_path)
```

2024-03-19 05:13 UTC, mnrkbys commented
Thanks for your comment.
I have updated shell.py again and rebased on the latest main.

2024-03-29 09:44 UTC, merged