Put plugins in the proper unix or linux namespace
fox-it/dissect.target pull request #447
Opened 2023-11-17 08:59 UTC by pyrco

(DIS-1996)

2023-11-18 01:50 UTC, Schamper requested changes

2023-11-18 01:50 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/packagemanager.py
This doesn't necessarily has to be moved, has it? BSD-likes also have a package manager? We don't have any parsers for those currently, but that doesn't mean we won't want to add them to here.

2023-11-20 10:53 UTC, pyrco commented on dissect/target/plugins/os/unix/linux/packagemanager.py
This plugin is for installation logs only, the pacakge manager specific database plugins are in the various subdirectories. OpenBSD does not log any package installation actions and FreeBSD logs to syslog (it doesn't have a default log file for package install logs only possibly site specific through syslog.conf), which means most install logs are probably rotated away and cleaned up. So support for the BSDs felt rather hypothetically.But if you think the FreeBSD case should be supported, Ill move it back.

2023-11-20 12:00 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/packagemanager.py
Ah, that's a fair comment. However, I still think it belongs in Unix because we might add package managers down the line that aren't exclusively Linux.

Speaking of, I don't think `esxi` is actually a Linux derivative. Would you also move that with this PR?

2023-11-20 20:00 UTC, Schamper commented on dissect/target/plugins/os/unix/packagemanager.py
> +        """Returns logs from all available unix package managers."""
```suggestion
        """Returns logs from all available Unix package managers."""
```

2023-11-21 07:46 UTC, Schamper approved these changes

2023-11-21 08:55 UTC, merged