Improve hash functionality
fox-it/dissect.target pull request #457
Opened 2023-11-24 14:04 UTC by Miauwkeru

(DIS-2623)

2023-11-24 16:16 UTC, pyrco requested changes

2023-11-24 16:16 UTC, pyrco commented on dissect/target/helpers/hashutil.py
> +RECORD_TYPES = ["path", "path", "digest"]
```suggestion
NAME_SUFFIXES = ["_resolved", "_digest"]
RECORD_TYPES = ["path", "digest"]
```
I don't think we need to duplicate the original path value. As we prepend the field names with the original fieldname, it is easy to see what the original path would have been.

2023-11-27 09:14 UTC, JSCU-CNI commented
Thanks for the heads-up @Miauwkeru.

2023-11-27 12:26 UTC, pyrco requested changes

2023-11-27 12:26 UTC, pyrco commented on dissect/target/helpers/hashutil.py
> +NAME_SUFFIXES = ["_resolved_path", "_digest"]
```suggestion
NAME_SUFFIXES = ["_resolved", "_digest"]
```

I'd still rename this, as a lot of filed names are or end with `"path"`, you'd get `path_resolved_path`, which doesn't look nice.

2023-11-27 13:35 UTC, pyrco approved these changes

2023-11-28 08:42 UTC, merged