Fix NamespacePlugin function filtering
fox-it/dissect.target pull request #463
Opened 2023-11-28 16:29 UTC by MaxGroot

While working on https://github.com/fox-it/dissect.target/pull/384, I ran into some issues with the `NamespacePlugin`.

- The previous check for subplugin export functions was too strict. It did not account for subplugins reusing export methods of subplugins. 
- Also improved handling `UnsupportedPlugin` exceptions, in favour of  handling any `Exception` with a `continue`.
- Lastly, added a check for when a subplugin has an export function with the same name as the `NamespacePlugin` subclass to which it belongs.
- Added tests for the scenarios outlined above.

2023-11-28 21:54 UTC, MaxGroot commented
@DissectBot agree

2024-01-11 12:40 UTC, cecinestpasunepipe requested changes

2024-01-11 12:40 UTC, cecinestpasunepipe commented on dissect/target/plugin.py
> +                            self.target.log.error("Subplugin %s raised an exception for %s", entry, method_name)
```suggestion
                            self.target.log.error("Subplugin: %s raised an exception for: %s", entry, method_name)
```

2024-01-11 12:40 UTC, cecinestpasunepipe commented on dissect/target/plugin.py
> +        # namespaceplugin and all of its superclasses.
```suggestion
        # namespaceplugin and all of its superclasses (minus the base object).
```

2024-01-11 12:52 UTC, Schamper requested changes

2024-01-11 12:52 UTC, Schamper commented on dissect/target/plugin.py
> +                            self.target.log.debug("Exception: %s", e, exc_info=True)
```suggestion
                            self.target.log.debug("Exception: %s", e, exc_info=e)
```

2024-01-13 10:40 UTC, Schamper approved these changes

2024-01-13 10:51 UTC, merged