Fix most tests for windows computers
fox-it/dissect.target pull request #467
Opened 2023-12-01 15:21 UTC by Miauwkeru

- Check whether effective_ids is enabled for the system
- Use __type__ consistently
- Open files as UTF-8 by default
- Fix paths in test_target.py
- Change all occurrences to flow.record path to self.target.fs.path
- Fix issues regarding the resolver in trusteddocs

2023-12-03 14:51 UTC, Schamper requested changes

2023-12-03 14:51 UTC, Schamper commented on dissect/target/helpers/cache.py
> +        effective_ids = True if os.supports_effective_ids else False
Can't you just put `effective_ids=os.supports_effective_ids` in all the calls?

2023-12-03 14:51 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/nixos/_os.py
Accidentally added or intentional addition? Missing a `__init__.py` if the latter case.

2023-12-03 14:51 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/trusteddocs.py
> +                    document_path=self.target.fs.path(self.target.resolve(value.name)),
Perhaps `.resolve()` should return a path?

2023-12-05 08:36 UTC, Poeloe requested changes

2023-12-05 08:36 UTC, Poeloe commented on dissect/target/plugins/os/windows/startupinfo.py
I guess you can remove the `from flow.record.fieldtypes import path` here as well, right?

2023-12-05 09:23 UTC, Poeloe approved these changes
LGTM

2023-12-06 08:48 UTC, merged