Add default docstrings to OSPlugin subclass methods
fox-it/dissect.target pull request #483
Opened 2023-12-12 16:03 UTC by pyrco

2023-12-20 17:47 UTC, Schamper requested changes

2023-12-20 17:47 UTC, Schamper commented on dissect/target/plugin.py
> +        """OSPlugin's use a different compatibility check, override the one from the Plugin class.
```suggestion
        """OSPlugin's use a different compatibility check, override the one from the :class:`Plugin` class.
```
I don't quite remember the syntax, but I think it was like this?

2023-12-20 17:47 UTC, Schamper commented on dissect/target/plugin.py
> +            This function always returns ``True``."""
```suggestion
            This function always returns ``True``.
        """
```

2023-12-20 23:43 UTC, Schamper requested changes

2023-12-20 23:43 UTC, Schamper commented on dissect/target/plugin.py
> +    methods with the same @classmethod or @export(...) annotation.
```suggestion
    methods with the same ``@classmethod`` or ``@export(...)`` annotation.
```

2023-12-21 08:09 UTC, pyrco commented on dissect/target/plugin.py
> +    methods with the same @classmethod or @export(...) annotation.
Changed a few more

2023-12-21 09:32 UTC, Schamper approved these changes

2023-12-21 10:02 UTC, merged