Add --resolve to target-query
fox-it/dissect.target pull request #485
Opened 2023-12-18 12:22 UTC by Miauwkeru

- Moves all the record modifier code to helpers/modifier.py
- Adds modifier logic, to allow for more modifiers to get added later (currently only paths get used)

- open the target_path during hashing:

When opened in a DirLoader, the OS will "open" the file
However, the file never got closed, so on linux you'd get
an error that the maximum open files threshold was reached

- Add tests for resolve

2023-12-18 12:45 UTC, Schamper requested changes

2023-12-18 12:45 UTC, Schamper commented on dissect/target/filesystem.py
> +        return hashutil.common(fd)
Where is `fd` coming from?

2023-12-18 12:45 UTC, Schamper commented on dissect/target/filesystem.py
I can't comment on it, but could you maybe also replace all instances of `List` in this file with `list`?

2023-12-18 12:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/firewall.py
> +                    data["app"] = str(self.target.resolve(data["app"]))
Shouldn't the `app` field in the record become a `path`?

2023-12-18 12:45 UTC, Schamper commented on dissect/target/tools/query.py
> +            modifier = modifier.Modifier.RESOLVE
Doesn't this conflict with the import name?

2023-12-20 08:04 UTC, pyrco requested changes

2023-12-20 08:04 UTC, pyrco commented on dissect/target/plugins/os/windows/regf/firewall.py
> +    FIELD_MAP = {"app": "path"}
Are you sure this is a path and not an uri?

2023-12-20 09:45 UTC, pyrco requested changes

2023-12-20 09:45 UTC, pyrco commented on dissect/target/helpers/modifier.py
> +    for type, name, field in type_info:
```suggestion
    for type, name, data in type_info:
```

2023-12-20 09:45 UTC, pyrco commented on dissect/target/helpers/modifier.py
> +        hashed_field_name = f"{field_name}{name}"
```suggestion
        extended_field_name = f"{field_name}{name}"
```

2023-12-20 09:45 UTC, pyrco commented on dissect/target/helpers/modifier.py
> +        yield target.resolve(str(path)), field_name
```suggestion
        yield field_name, target.resolve(str(path))
```

This order feels more logical (it is more in line with key, value pairs).

2023-12-20 09:45 UTC, pyrco commented on dissect/target/helpers/modifier.py
> +def _resolve_path_records(resolved_path: TargetPath, field_name: str) -> Record:
```suggestion
def _resolve_path_records(field_name: str, resolved_path: TargetPath) -> Record:
```
This order feels more logical (it is more in line with key, value pairs).

2023-12-20 09:45 UTC, pyrco commented on dissect/target/helpers/modifier.py
> +def _hash_path_records(resolved_path: TargetPath, field_name: str) -> Record:
```suggestion
def _hash_path_records( field_name: str, resolved_path: TargetPath) -> Record:
```
This order feels more logical (it is more in line with key, value pairs).

2023-12-22 14:53 UTC, pyrco requested changes

2023-12-22 14:53 UTC, pyrco commented on dissect/target/helpers/record_modifier.py
> +    additional_record = []
```suggestion
    additional_records = []
```

2023-12-22 14:53 UTC, pyrco commented on dissect/target/helpers/record_modifier.py
> +def _resolve_path_types(target: Target, record: Record) -> Iterable[tuple[TargetPath, str]]:
```suggestion
def _resolve_path_types(target: Target, record: Record) -> Iterator[tuple[str, TargetPath]]:
```

This actually is an Iterator ;)

2023-12-22 14:53 UTC, pyrco commented on dissect/target/helpers/record_modifier.py
> +def _create_modified_record(record_name: str, field_name: str, field_info: Iterable[tuple[str, str, str]]):
```suggestion
def _create_modified_record(record_name: str, field_name: str, field_info: Iterable[tuple[str, str, TargetPath]]):
```

2023-12-22 14:53 UTC, pyrco commented on dissect/target/helpers/record_modifier.py
> +    for type, name, data in field_info:
```suggestion
    for type, name_suffix, data in field_info:
```

2023-12-22 14:53 UTC, pyrco commented on dissect/target/helpers/hashutil.py
> +            "The hash_uri() function is deprecated, and will be removed in dissect.target 3.15."
```suggestion
            "The hash_uri() function is deprecated, and will be removed in dissect.target 3.15. "
```

The space should have been there as it's a continuation.

2023-12-22 14:53 UTC, pyrco commented on tests/helpers/test_modifier.py
> +    record_names = [key for key, value in test_input.items() if value is path]
```suggestion
    path_field_names = [key for key, value in test_input.items() if value is path]
```

2023-12-22 14:53 UTC, pyrco commented on tests/helpers/test_modifier.py
> +    _record = hashed_record.records[1]
```suggestion
    _record = hashed_record.records[1]
```

This looks like it is not being used.

2024-01-03 09:03 UTC, pyrco requested changes

2024-01-03 10:02 UTC, pyrco approved these changes

2024-01-03 10:15 UTC, merged