Fix the glob_ext() filesystem globbing function
fox-it/dissect.target pull request #489
Opened 2023-12-22 15:26 UTC by pyrco

When passed a pattern with path parts which did not contain any globs, the function would fail due to path strings instead of FilesystemEntry's being used.

Documentation and comments are added to the glob_ext*() functions and they are refactored a bit.

(DIS-2903)

2024-01-02 12:57 UTC, Schamper requested changes
Maybe also add a unit test for the previously failing case?

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    Split a pattern on path part boundaries on the first path part with a glob pattern.
```suggestion
    """Split a pattern on path part boundaries on the first path part with a glob pattern.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    Recursively search and return filesystem entries matching a given glob pattern.
```suggestion
    """Recursively search and return filesystem entries matching a given glob pattern.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    Match and return filesystem entries in a given filesystem entry based on pattern.
```suggestion
    """Match and return filesystem entries in a given filesystem entry based on pattern.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    Return the filesystem entry equal to the given path relative to direntry.
```suggestion
    """Return the filesystem entry equal to the given path relative to ``direntry``.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +              is the empty string (``''``) the ``direntry`` itself is returned.
```suggestion
              is an empty string (``''``) the ``direntry`` itself is returned.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    # (glob_ext).
```suggestion
    # If the pattern has more than one path part and these parts (dir_name) contain globs,
    # we recursively go over all the path parts and match them (glob_ext).
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    # (glob_ext0).
```suggestion
    # If these path parts have no globs, we get the path directly by name (glob_ext0).
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    # files in direntry.
```suggestion
    # The pattern has only one path part, so we can match directly against the files in direntry.
```

2024-01-02 12:57 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +            # match only directories.
```suggestion
            # Patterns ending with a slash, so without a base_name, should match only directories.
```

2024-01-02 16:35 UTC, Schamper commented
No regression unit test? :smile:

2024-01-03 10:01 UTC, pyrco commented
I added some tests :wink:

2024-01-03 10:47 UTC, Schamper approved these changes

2024-01-03 11:15 UTC, merged