Add PuTTY plugin (copy)
fox-it/dissect.target pull request #491
Opened 2024-01-02 09:17 UTC by JSCU-CNI

The local rebase was a bit of a mess so I've created a new PR.

See the previous PR for feedback history (https://github.com/fox-it/dissect.target/pull/418).

2024-01-02 09:33 UTC, Schamper requested changes

2024-01-02 09:48 UTC, JSCU-CNI commented on dissect/target/plugins/apps/ssh/putty.py
> +    ) -> tuple[list[set[RegistryKey, UserDetails | None]], list[set[TargetPath, UserDetails | None]]]:
added in [d647b7d](https://github.com/fox-it/dissect.target/pull/491/commits/d647b7d8b14e9b0a58cc3b8b26f3d543085c63df)

2024-01-05 09:27 UTC, Horofic approved these changes

2024-01-05 10:41 UTC, Schamper approved these changes

2024-01-05 10:42 UTC, merged