Added fix as per #DIS-2796
fox-it/dissect.target pull request #513
Opened 2024-01-23 16:42 UTC by florisvanstal

Wrote as fix for ticket DIS-2796, where the hostname could not be found for Red Hat systems. The hostname for these files is instead of /etc/hostname found within /etc/sysconfig/network.

2024-01-23 18:19 UTC, cecinestpasunepipe requested changes

2024-01-23 18:19 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/_os.py
> +        paths = paths or ["/etc/hostname", "/etc/HOSTNAME", "/etc/sysconfig/network"]
```suggestion
        REDHAT_LEGACY_PATH = "/etc/sysconfig/network"
        paths = paths or ["/etc/hostname", "/etc/HOSTNAME", REDHAT_LEGACY_PATH]
```

2024-01-23 18:19 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/_os.py
> +                if path == "/etc/sysconfig/network":
```suggestion
                if path == REDHAT_LEGACY_PATH:
```

2024-01-23 18:19 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/_os.py
```suggestion
def _parse_rh_legacy(self, path):
    file_contents = fs.path(path).open("rt").readlines()
    for line in file_contents:
        if not line.startswith("HOSTNAME"):
            continue
        _,_,hostname = line.rstrip().partition("=")
        return hostname
```


Also can you add a unit test for this new scenario?

2024-01-24 08:27 UTC, pyrco requested changes
Could you change the commit/PR message according to https://docs.dissect.tools/en/latest/contributing/style-guide.html#commit-message-style-and-formatting

2024-01-26 11:02 UTC, cecinestpasunepipe requested changes

2024-01-26 11:02 UTC, cecinestpasunepipe commented on tests/plugins/os/unix/test__os.py
> +        ("/etc/hostname", False, "myhost", None),
Also add some invalid cases please:

- invalid filename
- invalid file contents
- both with domain

2024-01-29 11:36 UTC, cecinestpasunepipe approved these changes
Tested on RH 7, works.

2024-01-29 15:59 UTC, cecinestpasunepipe approved these changes

2024-01-30 09:44 UTC, pyrco approved these changes

2024-01-31 10:14 UTC, merged