Add index of Shimcache entry to ShimcacheRecord
fox-it/dissect.target pull request #64
Opened 2022-10-13 13:59 UTC by Zawadidone

Fixes #63

2022-11-04 17:49 UTC, Schamper requested changes

2022-11-04 17:49 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/shimcache.py
> +        ("varint", "entry_index"),
```suggestion
        ("varint", "index"),
```
I think "entry" is already implied and thus redundant.

2022-11-04 17:49 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/shimcache.py
> +            entry_index (varint): The index of the entry.
```suggestion
            index (varint): The index of the entry.
```

2022-11-04 17:49 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/shimcache.py
> +                yield from self._get_records(cache, value_name)
```suggestion
                yield from self._get_records(value_name, cache)
```
Nitpicking, but you're passing the cache opened from `value_name`, so putting `value_name` first feels more natural.

2022-11-04 17:49 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/shimcache.py
> +        self, cache, name: Generator[ShimCacheGeneratorType, None, None]
```suggestion
        self, name: str, cache: Generator[ShimCacheGeneratorType, None, None]
```
Moving the order + fixing the type hint.

2022-11-04 17:49 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/shimcache.py
> +                entry_index=index+1,
Why not start counting at 0?

2022-11-07 22:23 UTC, Zawadidone commented
I will adjust the tests later on.

2022-11-22 00:28 UTC, Schamper approved these changes

2022-11-22 00:50 UTC, merged