Add Windows Jumplist plugin
fox-it/dissect.target pull request #669
Opened 2024-04-05 22:31 UTC by Zawadidone

```
target-query -t TARGET -f jumplist  --limit 1 | rdump -L
[reading from stdin]
--[ RECORD 1 ]--
          hostname = WINDEV2401EVAL
            domain = None
              type = customDestinations
    application_id = 590aee7bdd69b59b
  application_name = Powershell Windows 10
          lnk_path = C:\Users\User\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\590aee7bdd69b59b.customDestinations-ms
          lnk_name = None
         lnk_mtime = 2024-03-21 17:16:41.027615+00:00
         lnk_atime = 2024-03-21 17:16:40.997318+00:00
         lnk_ctime = 2024-03-21 17:16:29.070940+00:00
  lnk_relativepath = None
       lnk_workdir = None
     lnk_arguments = None
  lnk_iconlocation = %windir%\System32\WindowsPowerShell\v1.0\powershell.exe
   local_base_path = C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk
common_path_suffix = 
      lnk_net_name = None
   lnk_device_name = None
     lnk_full_path = C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk
        machine_id = windev2401eval
      target_mtime = 2022-05-07 05:22:32.504461+00:00
      target_atime = 2024-03-21 17:16:28.045404+00:00
      target_ctime = 2024-03-21 17:16:20.202059+00:00
          username = User
           user_id = S-1-5-21-147454635-2304731113-4176578439-1000
        user_group = None
         user_home = C:\Users\User
[...]
```

2024-07-19 12:07 UTC, Horofic requested changes

2024-08-05 09:31 UTC, Zawadidone commented on dissect/target/helpers/utils.py
> +def findall(buf, needle):
Fixed

2024-08-05 10:53 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def jumplist(self) -> Iterator[JumpListRecord]:
Is it a known issue that namespace plugins do not work?

`AttributeError: 'JumpListPlugin' object has no attribute 'SUBPLUGINS'`

2024-08-05 11:03 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +}
Fixed

2024-08-05 11:08 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def custom_destination(self) -> Iterator[JumpListRecord]:
Fixed

2024-08-05 11:08 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def automatic_destination(self):
Fixed

2024-08-05 11:09 UTC, Zawadidone commented on tests/test_plugins_os_windows_jumplist.py
Fixed

2024-08-05 11:23 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +            except NotImplementedError:
Fixed

2024-08-05 11:23 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +            if not custom_destination.MAGIC_FOOTER == custom_destination.magic:
Fixed

2024-08-05 11:44 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def name(self, name: str) -> tuple[Any, str, str]:
Fixed

2024-08-07 08:00 UTC, Horofic commented on dissect/target/plugins/os/windows/jumplist.py
> +    def jumplist(self) -> Iterator[JumpListRecord]:
An issue with nested namespaced plugin was reported here https://github.com/fox-it/dissect.target/issues/758 and fixed in this PR https://github.com/fox-it/dissect.target/pull/763. You could try and check-out this PR to see if you issue persists!

2024-08-12 12:58 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def jumplist(self) -> Iterator[JumpListRecord]:
The issue persists.

2024-08-14 12:17 UTC, Horofic requested changes

2024-08-14 12:18 UTC, Horofic commented
@Zawadidone I also committed some suggestions directly in your PR, please check if you see anything wrong :).

2024-08-14 14:33 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def automatic_destination(self) -> Iterator[JumpListRecord]:
Fixed

2024-08-14 14:33 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def custom_destination(self) -> Iterator[JumpListRecord]:
Fixed

2024-08-14 14:35 UTC, Zawadidone commented
[`f9fb309` (#669)](https://github.com/fox-it/dissect.target/pull/669/commits/f9fb30980789cf7562faa7c5abcdfbd6d8805f0b) includes is a change based on [`6464029` (#669)](https://github.com/fox-it/dissect.target/pull/669/commits/646402979f555eb0fcaeee97638046f0264fffd1), if this is not preferred I can remove the commit from the branch.

2024-08-15 09:25 UTC, Horofic commented
> [`f9fb309` (#669)](https://github.com/fox-it/dissect.target/pull/669/commits/f9fb30980789cf7562faa7c5abcdfbd6d8805f0b) is based on [`6464029` (#669)](https://github.com/fox-it/dissect.target/pull/669/commits/646402979f555eb0fcaeee97638046f0264fffd1), if this is not preferred I can remove the commit from the branch.

[6464029 (#669)](https://github.com/fox-it/dissect.target/pull/669/commits/646402979f555eb0fcaeee97638046f0264fffd1) is fine! That actually was the first approach I took :)

2024-08-15 09:31 UTC, Horofic requested changes

2024-08-15 09:31 UTC, Horofic commented on dissect/target/plugins/os/windows/jumplist.py
> +from typing import BinaryIO, Callable, Iterator
```suggestion
from __future__ import annotations

import io
import logging
from struct import error as StructError
from typing import BinaryIO, Iterator
```

2024-08-15 09:31 UTC, Horofic commented on dissect/target/plugins/os/windows/jumplist.py
> +    def _generate_records(self, destinations: list, destination_file: Callable) -> Iterator[JumpListRecord]:
```suggestion
    def _generate_records(
        self, destinations: list, destination_file: AutomaticDestinationFile | CustomDestinationFile
    ) -> Iterator[JumpListRecord]
```

2024-08-15 09:48 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +    def _generate_records(self, destinations: list, destination_file: Callable) -> Iterator[JumpListRecord]:
Fixed

2024-08-15 09:49 UTC, Zawadidone commented on dissect/target/plugins/os/windows/jumplist.py
> +from typing import BinaryIO, Callable, Iterator
Fixed

2024-08-15 09:51 UTC, Horofic approved these changes

2024-08-15 10:18 UTC, merged