Add thumbcache plugin
fox-it/dissect.target pull request #68
Opened 2022-10-27 09:56 UTC by Miauwkeru

2022-10-28 09:32 UTC, cecinestpasunepipe requested changes

2022-10-28 09:32 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/windows/thumbcache.py
> +    def plugin(self, record_type: TargetRecordDescriptor, prefix: str):
Return type?

2022-10-28 09:32 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/windows/thumbcache.py
> +    def thumbcache(self):
Return type?

2022-10-28 09:32 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/windows/thumbcache.py
> +    def iconcache(self):
Return type?

2022-10-28 09:32 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/windows/thumbcache.py
> +            if len(list(cache_path.glob("*_idx.db"))) > 0:
You can reduce this code with 1 line if you use:

```
if len(list(cache_path.glob("*_idx.db"))) == 0:
   raise UnsupportedPluginError("There was no cache path for that plugin")
```

2022-10-28 09:32 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/windows/thumbcache.py
> +                self.target.log.error(e)
Should there not be an additional explanation in this error message or is just the exception enough?

2022-10-28 10:38 UTC, Schamper requested changes

2022-10-28 10:38 UTC, Schamper commented on dissect/target/plugins/os/windows/thumbcache.py
> +IconcacheRecord = TargetRecordDescriptor("thumbcache/iconcache", GENERIC_THUMBCACHE_FIELDS)
```suggestion
ThumbcacheRecord = TargetRecordDescriptor("windows/thumbcache/thumbcache", GENERIC_THUMBCACHE_FIELDS)
IconcacheRecord = TargetRecordDescriptor("windows/thumbcache/iconcache", GENERIC_THUMBCACHE_FIELDS)
```

2022-10-28 10:38 UTC, Schamper commented on dissect/target/plugins/os/windows/thumbcache.py
> +    def plugin(self, record_type: TargetRecordDescriptor, prefix: str):
`plugin` is maybe a bit too generic of a function name. Maybe `_parse` or something?

2022-10-28 10:39 UTC, Schamper commented on setup.py
> +            "dissect.thumbcache>=0.0.dev,<1.0.dev" "dissect.xfs>=3.0.dev,<4.0.dev",
```suggestion
            "dissect.thumbcache>=0.0.dev,<1.0.dev",
            "dissect.xfs>=3.0.dev,<4.0.dev",
```

2022-10-28 10:39 UTC, Schamper commented on dissect/target/plugins/os/windows/thumbcache.py
> +    "thumbcache/index",
```suggestion
    "windows/thumbcache/index",
```

2022-10-31 10:09 UTC, Schamper commented on dissect/target/plugins/os/windows/thumbcache.py
> +    def thumbcache(self) -> Iterator[ThumbcacheRecord]:
Maybe add a `-o`/`--output` argument to extract the images? If that argument is given, extract the images to that directory.

2022-11-10 13:15 UTC, cecinestpasunepipe approved these changes

2022-11-10 13:16 UTC, merged