Add firefox extensions within firefox plugin
fox-it/dissect.target pull request #689
Opened 2024-04-24 12:06 UTC by M1ra1B0T

This PR adds the capability to parse firefox extensions (at least for Firefox 26+) to the firefox browser plugin. 
```
target-query -f firefox.extensions TARGET | rdump -L 
[reading from stdin]
[...]
--[ RECORD 12 ]--
           hostname = WINDOWS11
             domain = None
         ts_install = 2024-04-23 08:03:15+00:00
          ts_update = 2024-04-23 08:03:15+00:00
            browser = firefox
                 id = wappalyzer@crunchlabz.com
               name = Wappalyzer - Technology profiler
         short_name = None
      default_title = None
        description = Identify web technologies
            version = 6.10.68
           ext_path = C:\Users\Win11\AppData\Roaming\Mozilla\Firefox\Profiles\9nxit8q0.default-release\extensions\wappalyzer@crunchlabz.com.xpi
      from_webstore = None
        permissions = ['cookies', 'storage', 'tabs', 'webRequest']
   manifest_version = 2
             source = C:\Users\Win11\AppData\Roaming\Mozilla\Firefox\Profiles\9nxit8q0.default-release\extensions.json
          sourceURI = https://addons.mozilla.org/firefox/downloads/file/4239079/wappalyzer-6.10.68.xpi
optionalPermissions = ['downloads']
           username = Win11
            user_id = S-1-5-21-3098589626-1388384975-1619029170-1001
         user_group = None
          user_home = C:\Users\Win11
[...]
```

2024-04-25 14:30 UTC, Schamper requested changes

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                            name=extension.get("defaultLocale").get("name"),
```suggestion
                            name=extension.get("defaultLocale", {}).get("name"),
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                            description=extension.get("defaultLocale").get("description"),
```suggestion
                            description=extension.get("defaultLocale", {}).get("description"),
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                            permissions=extension.get("userPermissions").get("permissions"),
```suggestion
                            permissions=extension.get("userPermissions", {}).get("permissions"),
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                            optionalPermissions=extension.get("optionalPermissions").get("permissions"),
```suggestion
                            optional_permissions=extension.get("optionalPermissions", {}).get("permissions"),
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +FIREFOX_EXTENSION_RECORD_FIELDS = [("uri", "sourceURI"), ("string[]", "optionalPermissions")]
```suggestion
FIREFOX_EXTENSION_RECORD_FIELDS = [("uri", "source_uri"), ("string[]", "optional_permissions")]
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                            sourceURI=extension.get("sourceURI"),
```suggestion
                            source_uri=extension.get("sourceURI"),
```

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                    except (AttributeError, KeyError) as e:
```suggestion
                    except (AttributeError, KeyError) as e:
```
Maybe good to double check but with the proposed changes above, I don't think these can happen anymore.

2024-04-25 14:30 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +    BrowserExtensionRecord = create_extended_descriptor([UserRecordDescriptorExtension])(
For consistency sake, could you move this above the `BrowserPasswordRecord`?

2024-04-26 08:21 UTC, Schamper requested changes

2024-04-26 08:21 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                source (path): The source file of the download record.
```suggestion
        Yields BrowserExtensionRecord with the following fields::
            ts_install (datetime): Extension install timestamp.
            ts_update (datetime): Extension update timestamp.
            browser (string): The browser from which the records are generated.
            id (string): Extension unique identifier.
            name (string): Name of the extension.
            short_name (string): Short name of the extension.
            default_title (string): Default title of the extension.
            description (string): Description of the extension.
            version (string): Version of the extension.
            ext_path (path): Relative path of the extension.
            from_webstore (boolean): Extension from webstore.
            permissions (string[]): Permissions of the extension.
            manifest (varint): Version of the extensions' manifest.
            optional_permissions (string[]): Optional permissions of the extension.
            source_uri (path): Source path from which the extension was downloaded.
            source (path): The source file of the download record.
```

2024-04-26 08:21 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                        self.target.log.info("No browser extensions found in: %s", extension_file, exc_info=e)
```suggestion
                    yield self.BrowserExtensionRecord(
                        ts_install=extension.get("installDate", 0) // 1000,
                        ts_update=extension.get("updateDate", 0) // 1000,
                        browser="firefox",
                        id=extension.get("id"),
                        name=extension.get("defaultLocale", {}).get("name"),
                        short_name=None,
                        default_title=None,
                        description=extension.get("defaultLocale", {}).get("description"),
                        version=extension.get("version"),
                        ext_path=extension.get("path"),
                        from_webstore=None,
                        permissions=extension.get("userPermissions", {}).get("permissions"),
                        manifest_version=extension.get("manifestVersion"),
                        source_uri=extension.get("sourceURI"),
                        optional_permissions=extension.get("optionalPermissions", {}).get("permissions"),
                        source=extension_file,
                        _target=self.target,
                        _user=user.user,
                    )
```
Unless I'm mistaken I don't see anything that can raise these errors anymore.

2024-04-26 10:26 UTC, M1ra1B0T commented
@DissectBot agree

2024-04-26 12:54 UTC, Schamper approved these changes

2024-04-26 12:55 UTC, merged