Fix VBOX-Loader
fox-it/dissect.target pull request #69
Opened 2022-10-28 14:18 UTC by cecinestpasunepipe

Part of the VBOX-loader fix

(DIS-1430)

2022-10-31 09:05 UTC, Schamper requested changes

2022-10-31 10:42 UTC, cecinestpasunepipe commented on dissect/target/loaders/vbox.py
>              target.disks.add(VdiContainer(parent))
For some reason, if I do that, it raises an error and the vdi is not recognized anymore. I will look into this...

2022-10-31 14:48 UTC, cecinestpasunepipe commented on dissect/target/loaders/vbox.py
>              target.disks.add(VdiContainer(parent))
Adjusted, seems that VDI container was using the wrong magic number in detect()?

2022-10-31 15:42 UTC, Schamper commented on dissect/target/loaders/vbox.py
>              target.disks.add(VdiContainer(parent))
Ah interesting, correct magic number, wrong type :)

2022-10-31 15:43 UTC, Schamper submitted a review, later dismissed

2022-10-31 16:41 UTC, Schamper requested changes

2022-10-31 16:41 UTC, Schamper commented on tests/test_loaders_vbox.py
> +@patch("dissect.hypervisor.vdi.Vbox")
```suggestion
@patch("dissect.hypervisor.descriptor.vbox.VBox")
```

2022-11-01 14:38 UTC, Schamper approved these changes

2022-11-02 08:54 UTC, Schamper commented
I can't quite comment on it, but can you rename the class to `VBoxLoader` so it's more consistent with the other rename?

2022-11-02 09:45 UTC, Schamper approved these changes

2022-11-02 09:48 UTC, merged