Make ESXi Plugin work without crypto and fix vm_inventory
fox-it/dissect.target pull request #697
Opened 2024-05-01 12:15 UTC by Matthijsy

Currently the ESXi module works partly without having PyCryptodome installed, however this package is not 100% needed. Furthermore the vm_inventory method did always return the vm list. This PR does 3 things:

- Check if PyCryptodome or Pystandalone is availble, if not do not use the envelope
- Don't crash if there is no ESXi config, this makes the vm_inventory method available without crypto
- Creating the local layer after the mount modules

Currently the local layer is created before the mount modules. Some of these modules (in my case vim.v00) can contain empty `vmInventory.xml` files, which results in the `vm_inventory` method returning an empty list. By creating this local layer later the version in the local layer is used.

2024-05-13 09:50 UTC, Matthijsy commented
@DissectBot agree company="Northwave"

2024-05-27 11:29 UTC, Schamper requested changes

2024-05-27 11:29 UTC, Schamper commented on dissect/target/plugins/os/unix/esxi/_os.py
> +log = logging.getLogger(__name__)
```suggestion
```

2024-05-27 11:29 UTC, Schamper commented on dissect/target/plugins/os/unix/esxi/_os.py
> +import logging
```suggestion
```

2024-05-27 11:29 UTC, Schamper commented on dissect/target/plugins/os/unix/esxi/_os.py
> +            log.warning("No ESXi config!")
```suggestion
            self.target.log.warning("No ESXi config!")
```
We can use the target-bound logging to get additional context on the target where the warning occurred.

2024-07-01 09:24 UTC, Schamper approved these changes

2024-07-01 12:22 UTC, Schamper approved these changes

2024-07-01 12:23 UTC, merged