Add Rapid7 Velociraptor artifacts plugin
fox-it/dissect.target pull request #698
Opened 2024-05-01 14:54 UTC by Zawadidone

2024-05-01 14:56 UTC, Zawadidone commented
I have a few questions:
* Why doesn't this work (https://github.com/fox-it/dissect.target/pull/698/files#diff-d21a3f7b5a8a12a1531cd0193f1d5d28eed550ad78782baaf78ce79f25b66631R135-R139)? The file `uploads.json` is mapped correctly and exists in the root filesystem of the target but these files not.
* Why is there no record type `dict`, otherwise I will just use `str`? https://github.com/fox-it/dissect.target/pull/698/files#diff-b1b22daa6721c32ea013bfb6fcaabe0e1fc80d9d38988451a01e44503c7ac220R48

2024-12-18 13:48 UTC, Zawadidone commented
@Schamper any response?

2024-12-18 15:49 UTC, Schamper commented
> @Schamper any response?

I've brought this PR up internally with the team several weeks ago as I don't have much time to look into this until the new year, but doesn't look like anyone responded yet.

@EinatFox pinging again.

2025-04-10 11:05 UTC, Schamper requested changes
Can you also move `acquire_hash.py` and `acquire_handles.py` into a single `plugins/apps/edr/acquire.py` and make it a namespace? `acquire.hashes` and `acquire.handles` sounds nice.

2025-04-10 11:05 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +
```suggestion
```

2025-04-10 11:05 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +    def read_record(self, object: dict, target: Target):
Missing return type.

2025-04-10 11:05 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +        """Builds a Velociraptor record"""
```suggestion
        """Builds a Velociraptor record."""
```

2025-04-10 11:05 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +            # FIXME: Why is there no record type dict?
We have nested records, if that works for you. Otherwise you can raise an issue in `flow.record`.

2025-04-10 11:05 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +    def _create_event_descriptor(self, record_fields: tuple) -> TargetRecordDescriptor:
```suggestion
    def _create_event_descriptor(self, record_fields: list[tuple[str, str]]) -> TargetRecordDescriptor:
```

2025-04-25 09:48 UTC, Zawadidone commented on dissect/target/plugins/apps/edr/velociraptor.py
> +            # FIXME: Why is there no record type dict?
How do nested records work?

2025-04-25 09:50 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +            # FIXME: Why is there no record type dict?
There exists a `record` field type and the value is just any record. You can also use `record[]` for lists of records.

2025-04-25 09:52 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +            # FIXME: Why is there no record type dict?
https://github.com/fox-it/flow.record/blob/f4eba70f65e0f9a268f5e1421b06df1612a3acee/tests/test_packer.py#L200

Apparently we have `dictlist` too I just noticed 😄.

2025-04-25 11:58 UTC, Zawadidone commented on dissect/target/plugins/apps/edr/velociraptor.py
> +            # FIXME: Why is there no record type dict?
Thanks, `record` works fine

2025-04-25 12:08 UTC, Zawadidone commented
This is not blocking but the function `iterdir` works fine but when using `glob` the FS entries do not exist, which results in the exception `FileNotFoundError`: https://github.com/fox-it/dissect.target/pull/698/files#diff-b1b22daa6721c32ea013bfb6fcaabe0e1fc80d9d38988451a01e44503c7ac220R84-R86.

Is this normal behaviour of the filesystem?

2025-04-25 16:01 UTC, Schamper requested changes

2025-04-25 16:02 UTC, Schamper commented
> This is not blocking but the function `iterdir` works fine but when using `glob` the FS entries do not exist, which results in the exception `FileNotFoundError`: https://github.com/fox-it/dissect.target/pull/698/files#diff-b1b22daa6721c32ea013bfb6fcaabe0e1fc80d9d38988451a01e44503c7ac220R84-R86.
> 
> 
> 
> Is this normal behaviour of the filesystem?

Do you have a full stacktrace or otherwise a small reproducible snippet? I'm not really sure what you mean from just this description.

2025-04-28 14:46 UTC, Zawadidone commented on dissect/target/loaders/velociraptor.py
> +                if not artifact.name.endswith(".json") or not artifact.exists():
None as far as I know.

2025-04-28 15:00 UTC, Zawadidone commented
Listing the files with the function `iterdir` works correctly, but then an extra line of code is needed to skip non JSON files. The function `glob` could resolve this but it  does not work correctly as shown in the error below. 

I am curious whether this a bug in the filesystem implementation of Dissect or related to implementation of the `VelociraptorLoader`

```diff
diff --git i/dissect/target/plugins/apps/edr/velociraptor.py w/dissect/target/plugins/apps/edr/velociraptor.py
index 0a6250f9..08b96445 100644
--- i/dissect/target/plugins/apps/edr/velociraptor.py
+++ w/dissect/target/plugins/apps/edr/velociraptor.py
@@ -81,10 +81,7 @@ class VelociraptorPlugin(Plugin):
         References:
             - https://docs.velociraptor.app/docs/vql/artifacts/
         """
-        for artifact in self.results.iterdir():
-            if not artifact.name.endswith(".json"):
-                continue
-
+        for artifact in self.results.glob("*.json"):
             # "Windows.KapeFiles.Targets%2FAll\ File\ Metadata.json" becomes "windows_kapefiles_targets"
             artifact_name = (
                 urllib.parse.unquote(artifact.name.removesuffix(".json")).split("/")[0].lower().replace(".", "_")
```

```python
Traceback (most recent call last):
  File /dissect.target/dissect/target/helpers/compat/path_310.py", line 261, in get
    return self._entry
AttributeError: 'TargetPath' object has no attribute '_entry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dissect.target/.tox/py310/bin/target-query", line 8, in <module>
    sys.exit(main())
  File "/dissect.target/dissect/target/tools/utils.py", line 249, in wrapper
    return func(*args, **kwargs)
  File "/dissect.target/dissect/target/tools/query.py", line 386, in main
    for record in record_generator:
  File "/dissect.target/dissect/target/plugins/apps/edr/velociraptor.py", line 97, in velociraptor
    for line in artifact.open("rt"):
  File "/dissect.target/dissect/target/helpers/compat/path_310.py", line 391, in open
    return self._accessor.open(self, mode, buffering, encoding, errors, newline)
  File "/dissect.target/dissect/target/helpers/compat/path_310.py", line 91, in open
    return path_common.io_open(path, mode, buffering, encoding, errors, newline)
  File "/dissect.target/dissect/target/helpers/compat/path_common.py", line 216, in io_open
    raw = path.get().open()
  File "/dissect.target/dissect/target/helpers/compat/path_310.py", line 263, in get
    self._entry = self._fs.get(str(self))
  File "/dissect.target/dissect/target/filesystem.py", line 1628, in get
    entry = super().get(path, relentry)
  File "dissect.target/dissect/target/filesystem.py", line 1479, in get
    raise FileNotFoundError(full_path)
dissect.target.exceptions.FileNotFoundError: /$velociraptor_results$/Windows.Network.NetstatEnriched%2FNetstat.json
```

2025-04-29 08:46 UTC, Schamper commented
I can't reproduce, should the unit test trigger this already? I made some small other changes but I don't think those should affect this.

2025-04-29 08:48 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +                value = {k.lower(): v for k, v in value.items()}
```suggestion
                value = self.build(value, target)
```
This is how a nested record should be serialized, but I'm not sure if that'll still work for your purpose?

2025-04-29 11:31 UTC, Zawadidone commented
The unit tests are not affected and the error occurred when using `target-query` on a Velociraptor collection. 

When using a virtual file system the issue does not occur, so the commit [`9ec0fd1` (#698)](https://github.com/fox-it/dissect.target/pull/698/commits/9ec0fd1f8f71adfdf7daaec0b59f021731c83900) fixed the issue.

2025-04-29 12:12 UTC, Schamper commented
Weird, but okay. If you address that last comment then this is good to go.

2025-04-29 12:54 UTC, Schamper commented on dissect/target/plugins/apps/edr/velociraptor.py
> +                value = {k.lower(): v for k, v in value.items()}
Hm not sure, perhaps we can argue for a `dict` type in `flow.record`. @yunzheng is currently on vacation though so that'll have to wait.

Another option is to flatten the dict to keys like `authenticode_programname`, `authenticode_issuername` etc.

2025-04-30 12:17 UTC, Zawadidone commented on dissect/target/plugins/apps/edr/velociraptor.py
> +                value = {k.lower(): v for k, v in value.items()}
Okay I am fine with leaving the code as is with the nested records. I have created an issue (https://github.com/fox-it/dissect.target/issues/1128) for the support of the field type `dict`.

2025-05-01 06:58 UTC, merged