Indicate when cache is used
fox-it/dissect.target pull request #710
Opened 2024-05-21 14:44 UTC by narimantos

indicate when cache is used
(DIS-2985)

2024-05-22 14:36 UTC, Schamper requested changes

2024-05-22 14:36 UTC, Schamper commented on dissect/target/helpers/cache.py
> +                        return cache_data
```suggestion
                        reader = self.open_reader(cache_file, output)
                        target.log.info("Using cache for function: %s", self.fname)
                        return reader
```

2024-05-22 15:39 UTC, cecinestpasunepipe approved these changes

2024-05-23 08:28 UTC, Schamper approved these changes

2024-05-23 08:54 UTC, merged