Fix NoneType AttributeError in firefox extension plugin
fox-it/dissect.target pull request #713
Opened 2024-05-23 12:28 UTC by M1ra1B0T

This PR fixes a NoneType AttributeError in the firefox extension plugin.
When parsing the firefox extension information from the json file, we use the dictionary get method to access the relevant key value pairs. However, I ran into an uncatched NoneType AttributeError if the original key value is None, but we expect a nested dictionary, e.g. for the "name" field.

Additionally, the error message was slightly adapted, so instead of logging the whole user object, it now only prints the username as it should.

2024-07-10 14:22 UTC, Schamper commented
Do you have some test data or could you add some data to the unit test for this? Maybe I'm missing something but on first glance the previous code should be functionality identical?

```python
In [1]: extension = {}

In [2]: repr(extension.get("defaultLocale", {}).get("name"))
Out[2]: 'None'

In [3]: extension = {"defaultLocale": {}}

In [4]: repr(extension.get("defaultLocale", {}).get("name"))
Out[4]: 'None'
```

2024-07-15 08:12 UTC, M1ra1B0T commented
@Schamper The error occurs if the field `defaultLocale` is actually `None`.

```
>>> extension = {"defaultLocale": None}
>>> repr(extension.get("defaultLocale", {}).get("name"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
```

2024-07-18 11:03 UTC, Schamper requested changes
Suggested something a bit more concise.

2024-07-18 11:03 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                        else extension.get("defaultLocale", {}).get("name"),
```suggestion
                        name=(extension.get("defaultLocale", {}) or {}).get("name"),
```

2024-07-18 11:03 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                        else extension.get("defaultLocale", {}).get("description"),
```suggestion
                        description=(extension.get("defaultLocale", {}) or {}).get("description"),
```

2024-07-18 11:03 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                        else extension.get("userPermissions", {}).get("permissions"),
```suggestion
                        permissions=(extension.get("userPermissions", {}) or {}).get("permissions"),
```

2024-07-18 11:03 UTC, Schamper commented on dissect/target/plugins/apps/browser/firefox.py
> +                        else extension.get("optionalPermissions", {}).get("permissions"),
```suggestion
                        optional_permissions=(extension.get("optionalPermissions", {}) or {}).get("permissions"),
```

2024-07-18 11:24 UTC, Schamper approved these changes

2024-07-18 11:39 UTC, merged

2024-07-18 11:39 UTC, Schamper commented
Thanks! Was actually running into this issue too while working on another feature.