Add ls parameters to target-fs
fox-it/dissect.target pull request #716
Opened 2024-05-29 14:47 UTC by DevJoost

Add ls -ah functionality to target-fs

Mainly based it on the target-shell implementation. Also added -h (human readable) implementation that is missing in target-shell.

Resolves #626

2024-06-27 12:56 UTC, pyrco requested changes
Nice addition, 2 very small things, but otherwise lgtm.

2024-06-27 12:56 UTC, pyrco commented on dissect/target/tools/fs.py
> +def human_size(bytes, units=["", "K", "M", "G", "T", "P", "E"]):
Could you add type hints here also?

2024-06-27 12:56 UTC, pyrco commented on dissect/target/tools/fs.py
>  def ls(t, path, args):
```suggestion
def ls(t, path, args):
```

Since you're changing the whole function anyways, could you add type hints here also ;-)

2024-08-01 10:32 UTC, Schamper approved these changes

2024-08-01 12:36 UTC, pyrco approved these changes

2024-08-01 12:38 UTC, merged