Add support for deleted files in deleted RecycleBin directories
fox-it/dissect.target pull request #718
Opened 2024-05-30 13:38 UTC by DevJoost

Add support for deleted files in deleted RecycleBin directories

Also made some minor changes to variable names to make it more clear what function does what. 

Resolves #638

2024-07-10 14:34 UTC, Schamper requested changes

2024-07-10 14:34 UTC, Schamper commented on dissect/target/plugins/os/windows/recyclebin.py
> +    def read_recycle_file(self, path: TargetPath) -> Generator[RecycleBinRecord, None, None]:
```suggestion
    def read_recycle_file(self, path: TargetPath) -> Iterator[RecycleBinRecord]:
```

2024-07-10 14:34 UTC, Schamper commented on dissect/target/plugins/os/windows/recyclebin.py
> +        """
```suggestion
        # Generally speaking when deleting a file, the $R* file is the actual renamed deleted file.
        # This is however also the case for deleted folders. When a folder is deleted,
        # it is also renamed and placed here (with original recursive content).
        #
        # This function will create RecycleBin records for each file in a deleted folder.
```
This reads more like a code comment than a docstring.

2024-07-10 14:34 UTC, Schamper commented on dissect/target/plugins/os/windows/recyclebin.py
> +    def read_recycle_deleted_folder(self, folder_path: TargetPath) -> RecycleBinRecord:
```suggestion
    def read_recycle_deleted_folder(self, path: TargetPath) -> RecycleBinRecord:
```
And rename accordingly.

2024-07-10 14:34 UTC, Schamper commented on dissect/target/plugins/os/windows/recyclebin.py
> +        for parent_path, _, childs in folder_path.walk():
Maybe `rglob` works better for you? Then you don't have to do the nasty path construction at line 156 and 157.

2026-04-14 15:03 UTC, skepppy commented
It appears that this PR has become redundant, as this issue seems to have been fixed in #1377

2026-04-14 17:09 UTC, Schamper commented
> It appears that this PR has become redundant, as this issue seems to have been fixed in #1377

Closing.

2026-04-14 17:09 UTC, closed without merging