Improve parsing speed of walkfs plugins
fox-it/dissect.target pull request #749
Opened 2024-07-16 15:47 UTC by JSCU-CNI

Inspired by https://github.com/fox-it/dissect.ntfs/pull/35 we profiled and improved the `walkfs` plugin. By removing the unnecessary `FilesystemEntry` -> `TargetPath` -> `FilesystemEntry` conversion we see ~ 2x speed improvement on varying underlying container and filesystem formats.

We also introduced `fsutil.walk_ng` since we missed a function that returns a plain iterator for `FilesystemEntry`s instead of tuple separated files, folders and parent paths.

When refactoring the `walkfs` plugin we also had to refactor the `capabilities` plugin to match it's new record structure.

We currently have not added any extra tests that show the speed improvement we have experienced, however we noticed the https://github.com/fox-it/dissect.target/pull/747 PR, which seems to be using some form of `pytest-benchmark`. That certainly looks promising for the dissect project.

Please let us know if `walkfs_ng` should be renamed to something else, consider it a placeholder for a better function name :)

2024-07-19 14:03 UTC, pyrco requested changes
Very nice find of the unnecessary double conversion!

2024-07-24 19:47 UTC, Schamper commented on dissect/target/filesystem.py
> +    def walk_ng(self, path: str) -> Iterator[FilesystemEntry]:
`recurse`?

2024-07-25 11:27 UTC, Schamper commented on dissect/target/filesystem.py
> +    def walk_ng(self, path: str) -> Iterator[FilesystemEntry]:
Just `recurse`, leave out the `walk`.

2024-07-26 10:18 UTC, pyrco requested changes

2024-07-26 10:18 UTC, pyrco commented on dissect/target/helpers/fsutil.py
> +            yield from walk_ng(child_entry)
```suggestion
    yield path_entry
    
    if not path_entry.is_dir():
        return

    for child_entry in path_entry.scandir():
    
        if child_entry.is_dir() and not child_entry.is_symlink():
            yield from walk_ng(child_entry)
        else:
            yield child_entry
```

This should return the same results for the walkfs plugin (avoid the duplicate outputs) I think.

2024-08-19 12:08 UTC, Schamper requested changes
I have some additional suggestions for the capability changes too:

```diff
diff --git a/dissect/target/plugins/filesystem/unix/capability.py b/dissect/target/plugins/filesystem/unix/capability.py
index 4485994..97095dc 100644
--- a/dissect/target/plugins/filesystem/unix/capability.py
+++ b/dissect/target/plugins/filesystem/unix/capability.py
@@ -1,4 +1,3 @@
-import struct
 from enum import IntEnum
 from io import BytesIO
 from typing import Iterator
@@ -86,8 +85,8 @@ class CapabilityPlugin(Plugin):
         if not self.target.has_function("walkfs"):
             raise UnsupportedPluginError("Need walkfs plugin")
 
-        if self.target.os == "windows":
-            raise UnsupportedPluginError("Walkfs not supported on Windows")
+        if not any(fs.__type__ in ("extfs", "xfs") for fs in self.target.filesystems):
+            raise UnsupportedPluginError("Capability plugin only works on EXT and XFS filesystems")
 
     @export(record=CapabilityRecord)
     def capability_binaries(self) -> Iterator[CapabilityRecord]:
@@ -111,7 +110,7 @@ class CapabilityPlugin(Plugin):
 
             for attr in attrs:
                 try:
-                    parsed_attr = parse_attr(attr, BytesIO(attr.value))
+                    permitted, inheritable, effective, root_id = parse_attr(attr.value)
                 except ValueError as e:
                     self.target.log.warning("Could not parse attributes for entry %s: %s", entry, str(e.value))
                     self.target.log.debug("", exc_info=e)
@@ -119,19 +118,25 @@ class CapabilityPlugin(Plugin):
                 yield CapabilityRecord(
                     ts_mtime=entry.lstat().st_mtime,
                     path=entry.path,
-                    **parsed_attr,
+                    permitted=permitted,
+                    inheritable=inheritable,
+                    effective=effective,
+                    root_id=root_id,
                     _target=self.target,
                 )
 
 
-def parse_attr(attr: object, buf: BytesIO) -> dict:
+def parse_attr(attr: bytes) -> tuple[int, list[str], list[str], bool]:
     """Efficiently parse a Linux xattr capability struct.
 
-    Returns: dictionary of parsed capabilities for the given entry.
+    Returns:
+        A tuple of permitted capability names, inheritable capability names, effective flag and ``root_id``.
     """
+    buf = BytesIO(attr)
 
-    # The struct is small enough we can just use struct
-    magic_etc = struct.unpack("<I", buf.read(4))[0]
+    # The struct is small enough we can just use int.from_bytes
+    magic_etc = int.from_bytes(buf.read(4), "little")
+    effective = magic_etc & VFS_CAP_FLAGS_EFFECTIVE != 0
     cap_revision = magic_etc & VFS_CAP_REVISION_MASK
 
     permitted_caps = []
@@ -153,16 +158,15 @@ def parse_attr(attr: object, buf: BytesIO) -> dict:
     else:
         raise ValueError("Unexpected capability revision '%s'" % cap_revision)
 
-    if data_len != (actual_len := len(attr.value)):
+    if data_len != (actual_len := len(attr)):
         raise ValueError("Unexpected capability length (%s vs %s)", data_len, actual_len)
 
     for _ in range(num_caps):
-        permitted_val, inheritable_val = struct.unpack("<2I", buf.read(8))
-        permitted_caps.append(permitted_val)
-        inheritable_caps.append(inheritable_val)
+        permitted_caps.append(int.from_bytes(buf.read(4), "little"))
+        inheritable_caps.append(int.from_bytes(buf.read(4), "little"))
 
     if cap_revision == VFS_CAP_REVISION_3:
-        root_id = struct.unpack("<I", buf.read(4))[0]
+        root_id = int.from_bytes(buf.read(4), "little")
 
     permitted = []
     inheritable = []
@@ -178,9 +182,4 @@ def parse_attr(attr: object, buf: BytesIO) -> dict:
             if caps[cap_index] & (1 << (capability.value & 31)) != 0:
                 results.append(capability.name)
 
-    return {
-        "root_id": root_id,
-        "permitted": permitted,
-        "inheritable": inheritable,
-        "effective": magic_etc & VFS_CAP_FLAGS_EFFECTIVE != 0,
-    }
+    return permitted, inheritable, effective, root_id
diff --git a/tests/plugins/filesystem/unix/test_capability.py b/tests/plugins/filesystem/unix/test_capability.py
index cf1b8b8..5a4edc2 100644
--- a/tests/plugins/filesystem/unix/test_capability.py
+++ b/tests/plugins/filesystem/unix/test_capability.py
@@ -1,10 +1,11 @@
 from unittest.mock import Mock
 
-from dissect.target.filesystem import VirtualFile
+from dissect.target.filesystem import VirtualFile, VirtualFilesystem
 from dissect.target.plugins.filesystem.unix.capability import CapabilityPlugin
+from dissect.target.target import Target
 
 
-def test_capability_plugin(target_unix, fs_unix):
+def test_capability_plugin(target_unix: Target, fs_unix: VirtualFilesystem) -> None:
     # Some fictional capability values
     xattr1 = Mock()
     xattr1.name = "security.capability"
@@ -33,7 +34,7 @@ def test_capability_plugin(target_unix, fs_unix):
     vfile3.lattr.return_value = [xattr3]
     fs_unix.map_file_entry("/path/to/xattr3/file", vfile3)
 
-    target_unix.add_plugin(CapabilityPlugin)
+    target_unix.add_plugin(CapabilityPlugin, check_compatible=False)
 
     results = list(target_unix.capability_binaries())
     assert len(results) == 3
```

#826 should make this neater in the future too.

2024-08-19 12:08 UTC, Schamper commented on dissect/target/helpers/fsutil.py
> +    """Recursively walk the given FilesystemEntry, yields FilesystemEntry instances."""
Can you properly docstring these references to `FilesystemEntry` too?

2024-08-19 12:41 UTC, Schamper requested changes

2024-08-19 12:41 UTC, Schamper commented on dissect/target/plugins/filesystem/unix/capability.py
> +
```suggestion
```

2024-08-19 12:41 UTC, Schamper commented on dissect/target/plugins/filesystem/unix/capability.py
> +                    path=entry.path,
```suggestion
                    path=self.target.fs.path(entry.path),
```
I think this is the proper way to pass a path string to a `flow.record` `path` type.

2024-08-19 12:41 UTC, Schamper commented on dissect/target/plugins/filesystem/unix/capability.py
> +def parse_attr(attr: bytes) -> tuple[int, list[str], list[str], bool]:
```suggestion
def parse_attr(attr: bytes) -> tuple[list[str], list[str], bool, int]:
```
My bad, I changed the order later :smile:.

2024-08-21 08:24 UTC, Schamper requested changes

2024-08-21 08:24 UTC, Schamper commented on dissect/target/filesystem.py
> +    ) -> Iterator[tuple[str, str, str]]:
```suggestion
    ) -> Iterator[tuple[str, list[str], list[str]]]:
```

2024-08-21 08:24 UTC, Schamper commented on dissect/target/filesystem.py
> +    ) -> Iterator[tuple[str, str, str]]:
```suggestion
    ) -> Iterator[tuple[str, list[str], list[str]]]:
```

2024-08-21 10:25 UTC, Schamper approved these changes

2024-08-22 11:19 UTC, merged