Initial commit for plugin internals refactor
fox-it/dissect.target pull request #763
Opened 2024-07-25 14:46 UTC by Schamper

Initial commit for the plugin internals refactor. There are some things I want to add, but I may do those in a separate PR:
- Re-add support for https://github.com/fox-it/dissect.target/issues/758 (it was lost in between version 2 and 3)
- Add support for "plugin directories", similar to `_os.py`, but then `_plugin.py` or something similar
- Add helper functions for getting runtime information from functions, e.g. the class object, the record descriptor objects, etc. This will _finally_ allow us to query plugins by e.g. ones that generate records that have a `path` field, for example.

This should also cover https://github.com/fox-it/dissect.target/pull/759.

2024-11-26 10:41 UTC, pyrco requested changes
I noticed `plugins/general/example.py` and `plugins/os/unix/packagemanager.py` still have a `__findable__` property, which is now no longer needed.

Another thing I noticed is that the `-l` no longer lists the plugins from `_os.py`.

And a third thing I noticed that if I run a namespace plugin, e.g. webserver.access, which is listed when doing `target-query MyTarget -l`, before it printed an error like:

```
Error while parsing sysvol/windows/system32/inetsrv/config/applicationHost.config: ...
```
but now it errors with:
```
target-query: error: argument -f/--function contains invalid plugin(s): webserver.access
```

2024-11-26 10:41 UTC, pyrco commented on tests/test_plugin.py
> +MOCK_PLUGINS_OLD = {
As this is no longer used, it can be removed I think?

2024-12-16 14:35 UTC, Schamper commented on dissect/target/plugin.py
> +    for value in _get_plugins().get("__functions__", {}).get(None, {}).values():
I'm not sure on what the behaviour for that should be, as there are no existing unit tests for it. I assume it's not intended behaviour.

2024-12-16 15:03 UTC, Schamper commented
> I noticed `plugins/general/example.py` and `plugins/os/unix/packagemanager.py` still have a `__findable__` property, which is now no longer needed.

Fixed package manager but we still don't want the example plugin to findable.
 
> Another thing I noticed is that the `-l` no longer lists the plugins from `_os.py`.

Should be fixed again.

> And a third thing I noticed that if I run a namespace plugin, e.g. webserver.access, which is listed when doing `target-query MyTarget -l`, before it printed an error like:
> 
> ```
> Error while parsing sysvol/windows/system32/inetsrv/config/applicationHost.config: ...
> ```
> 
> but now it errors with:
> 
> ```
> target-query: error: argument -f/--function contains invalid plugin(s): webserver.access
> ```

I had to largely rewrite the `NamespacePlugin` to properly behave without any of its old side effects, but this is now also fixed.

2025-01-23 09:42 UTC, twiggler requested changes
Nice increment.

Left some comments, most are suggestions / ideas, not demands.

QA: did not find regressions but will test again after changes.

2025-01-23 09:42 UTC, twiggler commented on dissect/target/plugin.py
> +        "__child__": {},
(Nitpick)

Discriminating between child and regular plugins is done for performance it seems? Perhaps somewhat better to  localize the distinction and add memoization to  `child_plugins`.

2025-01-23 09:42 UTC, twiggler commented on dissect/target/plugin.py
> +    "__ostree__": {},
This also feels like derived state (i.e. more like a cache) so perhaps it is better to memoize the tree

2025-01-23 09:42 UTC, twiggler commented on dissect/target/plugin.py
> +    Additionally, ``register`` sets the following private attributes on the `plugincls`:
(Architecture question, somewhat inarticulate)

Should OSPlugins also be plugins? 
Maybe they should be pluggable, but is this registry the right place to handle them?
Because it seems we need to make exceptions for them throughout the functions below.

2025-01-24 15:50 UTC, Schamper commented on dissect/target/target.py
> +        """Override of the default ``__getattr__`` so plugins and functions can be called from a ``Target`` object."""
I have thought about this too, and this is indeed very annoying. However, I think the experience of being able to access any plugin as an attribute of the `Target` object is exactly what contributes to heavily to the "magic" of `dissect.target`.

An alternative "solution/workaround" I thought about would be a generated `target.pyi` stub file with every possible plugin attribute populated on the `Target` class. This stub file could be CI checked to be up to date with a pytest unit test, similarly to how we e.g. test that all test files are in Git LFS.

I must admit pushing the dependencies to the plugin is interesting from a different perspective. Maybe something to talk about later.

2025-01-24 15:57 UTC, Schamper commented on dissect/target/plugin.py
> +        None: dict[str, PluginDescriptor],
I have a slight personal preference for the `__` syntax, to indicate that they are special root keys. But I will change the `None` out.

2025-01-24 16:04 UTC, Schamper commented on dissect/target/plugin.py
> +        for key, value in _get_plugins().get("__plugins__", {}).get(index, {}).items()
I will try to make this a bit easier. I had different helper functions before, but they were considerable slowdowns. I wanted this function to be as fast as possible, so that's why it ended up being as one list comprehension.

2025-01-24 16:32 UTC, Schamper commented on dissect/target/plugin.py
> +        "__child__": {},
There's no (fast) way to distinct a `ChildTargetPlugin` from a regular plugin once they're in the registry. We only allow basic types in the registry so that it can be easily serialised. Child plugins are special cased and only used in the opening on child targets, so they can't be used in the same places that regular plugins can.

I don't think there's a much better way to mix these.

2025-01-24 16:34 UTC, Schamper commented on dissect/target/plugin.py
> +    "__ostree__": {},
This is indeed a cache, but the important difference between this and memoization is that memoization would need to occur on every first execution, whereas with this we can benefit from a pre-cached index if we deserialise the plugin index.

2025-01-24 16:44 UTC, Schamper commented on dissect/target/plugin.py
> +def export(*args, **kwargs) -> Callable[..., Any]:
I'm personally okay with the current state of things, but it is reaching the limits. Let's look at that at some different time.

2025-01-24 16:48 UTC, Schamper commented on dissect/target/plugin.py
> +The plugin registry can be stored in a file and loaded later. Plain Python syntax is used to store the registry.
The `TypedDict` is currently only to increase type hinting.

Do you think it should be a concern for this PR? I think it can be handled separately, as I think we won't touch the data structure with that change, just the way it's serialised/deserialised.

2025-01-24 16:48 UTC, Schamper commented on dissect/target/plugin.py
> +        for entry in _get_plugins().get("__functions__", {}).get(index, {}).values()
Added some more descriptive names.

2025-01-24 16:49 UTC, Schamper commented on dissect/target/plugin.py
> +def find_plugin_functions(
Tried to do what you suggested.

2025-01-27 10:25 UTC, twiggler commented on dissect/target/plugin.py
> +    registry = _get_plugins()
```
class PluginRegistry:
   plugins: PluginDescriptor[]
   functions: FunctionDescriptor[]
   ostree: dict[str, PluginDescriptor]
   ...

   # Also does serialization and deserialization 
   
   def find_plugin_functions(self, ....)

   def filter_compatible(self, ...)
```

2025-01-27 12:08 UTC, twiggler commented on dissect/target/target.py
> +        """Override of the default ``__getattr__`` so plugins and functions can be called from a ``Target`` object."""
> Maybe something to talk about later.

Sure!

> An alternative "solution/workaround" I thought about would be a generated target.pyi stub file with every possible plugin attribute populated on the Target class. This stub file could be CI checked to be up to date with a pytest unit test, similarly to how we e.g. test that all test files are in Git LFS.

Not a bad idea.

2025-01-27 13:29 UTC, Schamper commented
> Additionally could `FunctionDescriptor.record` be populated with `__record__` as discussed in #759?

This is not possible since we can't serialise the record descriptor, so it would just be a string. This functionality will be part of an incremental improvement of this PR as discussed in the main PR body:

> - Add helper functions for getting runtime information from functions, e.g. the class object, the record descriptor objects, etc. This will finally allow us to query plugins by e.g. ones that generate records that have a path field, for example.

The goal of this PR is to agree and establish a better base plugin system, and then incrementally improve that.

2025-01-29 10:27 UTC, twiggler commented on dissect/target/plugin.py
> +    Additionally, ``register`` sets the following private attributes on the `plugincls`:
`find_plugin_functions` depends on `__functions__.__os__`.
And there is the `osfilter` in `plugins` and `functions` and `lookup`.

But I don´t have a solution, at this point I cannot even articulate the problem.
Only a nagging feeling.

Let's close for now.

2025-01-29 10:28 UTC, twiggler requested changes
Code looks good.

Some tests are failing though.

After these have been fixed, I will do another QA pass.

2025-01-30 09:43 UTC, twiggler approved these changes

2025-01-30 10:37 UTC, merged

2025-01-30 11:10 UTC, Schamper commented
And otherwise https://github.com/fox-it/dissect.target/pull/1007 hopefully improves on that 😄