Add MCAB-formatting to MFT
fox-it/dissect.target pull request #767
Opened 2024-07-29 11:13 UTC by cecinestpasunepipe

(DIS-2755)

2024-07-29 12:10 UTC, Schamper requested changes

2024-07-29 12:10 UTC, Schamper commented on dissect/target/plugins/filesystem/ntfs/mft.py
> +    "filesystem/ntfs/mft/mcab",
```suggestion
    "filesystem/ntfs/mft/macb",
```
And everywhere else.

2024-07-30 11:16 UTC, Schamper requested changes

2024-07-30 11:16 UTC, Schamper commented on dissect/target/plugins/filesystem/ntfs/mft.py
> +    "filesystem/ntfs/mft/mcab",
```suggestion
    "filesystem/ntfs/mft/macb",
```

2024-07-31 11:01 UTC, Schamper requested changes

2024-07-31 11:01 UTC, Schamper commented on tests/plugins/filesystem/ntfs/test_mft.py
> +def test_mft_plugin_mcab(target_win: Target) -> None:
```suggestion
def test_mft_plugin_macb(target_win: Target) -> None:
```

2024-08-01 08:01 UTC, Poeloe requested changes

2024-08-01 08:01 UTC, Poeloe commented on tests/plugins/filesystem/ntfs/test_mft.py
> +            records.append(FilesystemFilenameRecord(path="a.txt", ts=makets(tss), ts_type=ts_type, ads=True))
```suggestion
    def make_ts(tss: set) -> int:
        ts = randrange(1, 10)
        tss.add(ts)
        return ts

    for _ in range(0, 100):
        tss = set()
        records = []
        for ts_type in ["M", "A", "C", "B"]:
            records.append(FilesystemStdRecord(path="a.txt", ts=make_ts(tss), ts_type=ts_type))
            records.append(FilesystemFilenameRecord(path="a.txt", ts=make_ts(tss), ts_type=ts_type, ads=False))
            records.append(FilesystemFilenameRecord(path="a.txt", ts=make_ts(tss), ts_type=ts_type, ads=True))
```

2024-08-01 09:16 UTC, Poeloe approved these changes
LGTM!

2024-08-01 09:40 UTC, merged