Fix issue with pathless config items
fox-it/dissect.target pull request #785
Opened 2024-08-02 13:14 UTC by cecinestpasunepipe

2024-08-02 15:17 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/etc/etc.py
> +                    "source": self.target.fs.path(config_entry.entry.path if hasattr(config_entry,"entry") else path),
Can you give an example regarding the first comment?

2024-08-02 15:58 UTC, cecinestpasunepipe commented on dissect/target/plugins/os/unix/etc/etc.py
> +                    "source": self.target.fs.path(config_entry.entry.path if hasattr(config_entry,"entry") else path),
Ah thanks

2024-08-12 09:26 UTC, Schamper requested changes

2024-08-12 09:26 UTC, Schamper commented on dissect/target/plugins/os/unix/etc/etc.py
> +        self, items: Union[ConfigurationEntry, dict], entry: Path, orig_path: Path, pattern: str
```suggestion
        self, items: ConfigurationEntry | dict, entry: Path, orig_path: Path, pattern: str
```

2024-08-12 09:26 UTC, Schamper commented on dissect/target/plugins/os/unix/etc/etc.py
> +from typing import Iterator, Union
```suggestion
from typing import Iterator
```

2024-11-21 13:41 UTC, merged