Add computer SID for Windows systems
fox-it/dissect.target pull request #824
Opened 2024-08-15 14:23 UTC by fox-evv

This addition to the generic Windows plugin exports the machine and domain SIDs
of the target. If the system is not joined to a domain, it uses only the/
SAM hive, but if the system is domain joined, it will all so use
the Security Policy.

2024-09-03 08:24 UTC, Horofic commented
@fox-evv I've suggested some changes and also added some test with this commit. One thing I could not verify myself is whether there can be multiple Machine / Domain SIDs. The initial implementation kind of seemed to suggest this. Do you encounter this scenario yourself? I left it out of this implementation because it seemed illogical to me.

2024-09-03 08:49 UTC, Horofic requested changes

2024-09-03 08:49 UTC, Horofic commented on dissect/target/plugins/os/windows/generic.py
> +            key = self.target.registry.key("HKLM\\SAM\\SAM\\Domains\\Account")
Can there be multiple Machine- and Domain SIDS associated with one system?

2024-11-01 11:59 UTC, Horofic approved these changes

2024-11-01 12:47 UTC, merged

2024-11-01 13:37 UTC, Schamper reviewed
@Horofic can you fix these notes or create a ticket for them?

2024-11-01 13:37 UTC, Schamper commented on tests/plugins/os/windows/test_generic.py
> +def test_windows_generic_sid(target_win: Target, hive_hklm: VirtualHive):
Missing return type hint

2024-11-01 13:37 UTC, Schamper commented on tests/plugins/os/windows/test_generic.py
> +def test_windows_generic_install_date(target_win_users: Target, hive_hklm: VirtualHive):
Missing return type hint

2024-11-01 13:37 UTC, Schamper commented on dissect/target/plugins/os/windows/generic.py
> +        ("string", "sidtype"),
Should be `type` and not `sidtype`.