Add Proxmox support
fox-it/dissect.target pull request #837
Opened 2024-09-02 10:42 UTC by Schamper

https://github.com/fox-it/dissect.target/pull/745 moved into our scope for uploading LFS files.

2024-09-13 08:24 UTC, Horofic requested changes

2024-09-13 12:34 UTC, Schamper commented on dissect/target/plugins/os/unix/linux/debian/proxmox/_os.py
> +        return None
This is more explicit and in line with all the other OS plugins.

2024-09-13 13:11 UTC, Horofic approved these changes

2024-10-30 10:18 UTC, Horofic approved these changes

2024-10-30 11:16 UTC, merged