Add Parallels child detection
fox-it/dissect.target pull request #855
Opened 2024-09-18 12:20 UTC by JSCU-CNI

This PR adds Parallels child detection for MacOS targets.

2024-09-19 13:12 UTC, Schamper requested changes

2024-09-19 13:12 UTC, Schamper commented on dissect/target/plugins/child/parallels.py
> +    """Finds virtual machines located in default folders on a MacOS target.
```suggestion
    """Finds virtual machines located in default folders on a macOS target.
```

2024-09-20 10:34 UTC, Schamper requested changes

2024-09-20 10:34 UTC, Schamper commented on dissect/target/plugins/child/parallels.py
> +def iter_vms(path: TargetPath) -> Iterator[TargetPath]:
```suggestion
def iter_vms(path: Path) -> Iterator[TargetPath]:
```

2024-09-20 10:34 UTC, Schamper commented on dissect/target/plugins/child/parallels.py
> +    def list_children(self):
```suggestion
    def list_children(self) -> Iterator[ChildTargetRecord]:
```

2024-09-20 10:34 UTC, Schamper commented on dissect/target/plugins/child/parallels.py
> +from typing import Iterator
```suggestion
from pathlib import Path
from typing import Iterator
```

2024-09-23 10:49 UTC, Schamper approved these changes

2024-09-23 10:53 UTC, Schamper requested changes
If you fix the linter in `tests/plugins/child/test_parallels.py` this is good to go.

2024-09-26 11:46 UTC, Schamper commented
I'm going on vacation and unfortunately don't have time to look at this now, I'll see if someone from the team can help :smile:

2024-09-27 16:26 UTC, twiggler commented
@JSCU-CNI I have created a fix for the root cause in a separate PR: https://github.com/fox-it/dissect.target/pull/867

After fix has been merged, you can rebase so that your unit test should pass when running on windows.

2024-10-03 09:29 UTC, twiggler commented
@JSCU-CNI https://github.com/fox-it/dissect.target/pull/867 has been merged, you can rebase

2024-10-07 09:20 UTC, Schamper approved these changes

2024-10-07 09:31 UTC, merged