Small log improvements
fox-it/dissect.target pull request #857
Opened 2024-09-19 09:59 UTC by JSCU-CNI

This PR addresses two small issues:

* The hash record modifier could generate a lot of warnings when combining the walkfs plugin with `--hash` as a lot of files can be broken. this log is now demoted to INFO for `FileNotFoundError`s as that exception is not really interesting in those instances.
* When entering a child target using `--children` or target-shell's `enter` the path of said child was appended to the locations of where to look for targetcfg files. That obviously does not work as that path is virtual inside the main target. This is now fixed.

Fixes #880 and fixes #881.

2024-10-02 09:00 UTC, EinatFox commented
Hi @JSCU-CNI , please open an issue and attache this PR so we can schedule a review into our sprints.

2024-10-07 10:45 UTC, Schamper requested changes

2024-10-07 10:45 UTC, Schamper commented on dissect/target/helpers/record_modifier.py
>              target.log.warning(
```suggestion
        except FilesystemError as e:
            level = logging.INFO if isinstance(e, FileNotFoundError) else logging.WARNING
            target.log.log(
                level,
```
Maybe a bit more concise. I played around with this or setting `target.log.warning`/`target.log.info` to a variable but I'm not sure if I have a specific preference.

2024-10-23 12:56 UTC, Schamper approved these changes

2024-10-23 14:50 UTC, merged