Add MUIcache plugin
fox-it/dissect.target pull request #87
Opened 2022-11-24 20:44 UTC by Zawadidone

WIP because of MUIcache values in different keys in with different formats shown as comments.

2022-11-25 09:15 UTC, Schamper requested changes

2022-11-25 09:15 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +                if entry.name.endswith(tuple(self.FIELD_NAMES)):
```suggestion
                if entry.name.endswith(tuple(self.FIELD_NAMES)):
```
If you make `self.FIELD_NAMES` a tuple itself, you don't need to make it a tuple here.

2022-11-26 19:00 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
The tests values are converted to strings and is checked against double-backslash Windows paths as seen here https://github.com/fox-it/flow.record/blob/main/tests/test_fieldtypes.py#L488.

2022-11-26 19:20 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
Is it an issue that the fieldname `path` in this plugin is not detected as `windows_path`, but `posix_path`?

```bash
$ target-query -f muicache -t MSEDGEWIN10_20220708124036.tar -q --limit 3 | rdump -F path
[reading from stdin]
<windows/registry/muicache path=posix_path('LanguageList')>
<windows/registry/muicache path=posix_path('@C:\\Windows\\system32\\windows.storage.dll')>
<windows/registry/muicache path=posix_path('@C:\\Windows\\system32\\NetworkExplorer.dll')>

$ target-query -f muicache -t MSEDGEWIN10_20220708124036.tar -q --limit 3 | rdump -L -F path
[reading from stdin]
--[ RECORD 1 ]--
path = LanguageList
--[ RECORD 2 ]--
path = @C:\Windows\system32\windows.storage.dll
--[ RECORD 3 ]--
path = @C:\Windows\system32\NetworkExplorer.dll
```

2022-11-28 09:07 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
If you don't cast it to a string that should work as intended:
```
path = _path.from_windows(path)
```

2022-11-29 21:19 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
Okay that line is adjusted.

`rdump` works with csv, line and the default record output, but json(lines) results in errors. Should I create a issue in the flow.record project?

```bash
python query.py -f muicache -t MSEDGEWIN10_20220708124036.tar -q --limit 3 | rdump -J
[reading from stdin]
{"_type": "recorddescriptor", "_data": ["windows/registry/muicache", [["string", "hostname"], ["string", "domain"], ["varint", "index"], ["string", "name"], ["string", "value"], ["path", "path"], ["string", "regf_hive_path"], ["string", "regf_key_path"], ["string", "username"], ["string", "user_id"], ["string", "user_home"]]]}
Traceback (most recent call last):
  File "[...]/dissect.target/.tox/py3/bin/rdump", line 8, in <module>
    sys.exit(main())
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/tools/rdump.py", line 212, in main
    record_writer.write(rec)
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/adapter/jsonfile.py", line 37, in write
    self._write(r)
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/adapter/jsonfile.py", line 33, in _write
    record_json = self.packer.pack(obj)
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/jsonpacker.py", line 93, in pack
    return json.dumps(obj, default=self.pack_obj, indent=self.indent)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "[...]/dissect.target/.tox/py3/lib/python3.10/site-packages/flow/record/jsonpacker.py", line 71, in pack_obj
    raise Exception("Unpackable type " + str(type(obj)))
Exception: Unpackable type <class 'flow.record.fieldtypes.windows_path'>
```

2022-11-30 09:18 UTC, yunzheng commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
Yes please

2022-11-30 12:00 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
https://github.com/fox-it/flow.record/issues/29

2022-11-30 21:31 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
Ah right

2022-11-30 21:34 UTC, Zawadidone commented on dissect/target/plugins/os/windows/regf/muicache.py
> +        ("uri", "path"),
https://github.com/fox-it/flow.record/issues/31

2022-12-01 13:45 UTC, Schamper requested changes
Small renaming changes.

2022-12-01 13:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +from flow.record.fieldtypes import path as _path
```suggestion
from flow.record.fieldtypes import path
```

2022-12-01 13:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +                    path, name = entry.name.rsplit(".", 1)
```suggestion
                    entry_path, name = entry.name.rsplit(".", 1)
```

2022-12-01 13:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +                    path = entry.name.rsplit(",-", 1)[0]
```suggestion
                    entry_path = entry.name.rsplit(",-", 1)[0]
```

2022-12-01 13:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +                    continue
```suggestion

                # Filter on the type of the registry value
                if isinstance(entry.value, bytes):
                    continue
```

2022-12-01 13:45 UTC, Schamper commented on dissect/target/plugins/os/windows/regf/muicache.py
> +                    path=path,
```suggestion
                    value=entry.value,
                    path=path.from_windows(entry_path),
```

2022-12-05 12:41 UTC, Schamper commented
Is this waiting on one or more bug fixes in flow.record or is this good to merge?

2022-12-05 13:49 UTC, Zawadidone commented
> Is this waiting on one or more bug fixes in flow.record or is this good to merge?

The bug is fixed in flow.record (https://github.com/fox-it/flow.record/issues/31) but dissect.target needs a dev version of the package (https://github.com/Zawadidone/dissect.target/blob/feature/add_plugin_muicache/setup.py#L63) to verify this. Can I adjust this or are dev versions not allowed?

`"flow.record>=3.0.dev,<4.0.dev"`

2022-12-05 14:24 UTC, Schamper commented
Is the bug specific to this MR or could this be merged and the version of flow.record bumped in a later fix? You can always install the development version of flow.record locally until a new version of flow.record is released:

```
pip install --upgrade --pre flow.record
```
You'll get a warning about conflicting versions but you can safely ignore that.

2022-12-05 14:38 UTC, Zawadidone commented
Okay merging is fine

2022-12-05 15:22 UTC, Schamper approved these changes

2022-12-05 15:22 UTC, merged