Add Python 3.13 compatibility
fox-it/dissect.target pull request #897
Opened 2024-10-09 14:03 UTC by JSCU-CNI

This PR aims to implement a TargetPath 3.13 variant. Fixes #895 and currently WIP.

- [x] Add 3.13 variant
- [x] Fix `scandir`
- [x] Fix `glob`
- [x] Fix `rglob`
- [x] Do we still need flavours?
- [x] ...

Resources:
- https://docs.python.org/3.13/whatsnew/3.13.html#pathlib
- https://github.com/python/cpython/blob/v3.13.0/Lib/pathlib/_local.py
- https://github.com/python/cpython/blob/v3.12.7/Lib/pathlib.py
- https://github.com/python/cpython/blob/v3.13.0/Lib/glob.py
- https://github.com/python/cpython/blob/v3.12.7/Lib/glob.py

2024-12-04 21:16 UTC, Schamper commented
Fixed up the rest, I believe only `flow.record` needs to add compatibility with 3.13 (`path` type).

2024-12-04 21:30 UTC, Schamper commented
Depends on https://github.com/fox-it/flow.record/pull/154

2024-12-05 11:11 UTC, Schamper commented
I didn't run the entire test suite yet with the flow.record fixes, so that probably still requires some looking into 😄

2024-12-05 21:23 UTC, Schamper commented
I saw that deprecation warning as well when looking at the pathlib changes, but the alternative is not really a good fit for Dissect. We don't really use that function anyway beside a unit test, so maybe remove it from the unit test and add a `fsutil.isreserved()` for completeness sake?

2025-01-09 13:16 UTC, Schamper commented
We have to bump that version anyway, so we'll just have to wait for a new release.

2025-01-10 12:38 UTC, Horofic requested changes

2025-01-10 12:38 UTC, Horofic commented on tests/test_container.py
>  import struct
For the Union types in `test_open_inputs()`
```suggestion
from __future__ import annotations

import struct
```

2025-01-10 12:40 UTC, Horofic commented on dissect/target/helpers/compat/path_313.py
> +    # NOTE: This is copied from pathlib/_local.py but turned into an instance method so we get access to the correct flavour
Linter fix
```suggestion
    # NOTE: This is copied from pathlib/_local.py 
    # but turned into an instance method so we get access to the correct flavour
```

2025-01-10 14:10 UTC, Horofic approved these changes

2025-01-11 10:46 UTC, Horofic approved these changes

2025-01-20 15:39 UTC, Schamper commented
Can be merged after a new release of `flow.record`.

2025-02-20 09:43 UTC, Schamper approved these changes

2025-02-20 22:24 UTC, merged