Add support for mounted GNOME Trash folders
fox-it/dissect.target pull request #906
Opened 2024-10-16 13:49 UTC by JSCU-CNI

This PR adds mounted Trash folder support to the GNOME Trash plugin. Fixes #908.

2024-10-16 13:52 UTC, Schamper requested changes

2024-10-16 13:52 UTC, Schamper commented on dissect/target/filesystem.py
> +    mounts: dict = {}
Is this addition only for the unit test? I'd prefer finding a more suitable way to mock in that case :smile:.

2024-10-30 13:12 UTC, Horofic requested changes

2024-10-30 13:12 UTC, Horofic commented on dissect/target/plugins/os/unix/trash.py
> +        for mount_path in list(self.target.fs.mounts.keys()) + ["/mnt", "/media"]:
```suggestion
        for mount_path in list(self.target.fs.mounts) + ["/mnt", "/media"]:
```

2024-10-30 13:12 UTC, Horofic commented on dissect/target/plugins/os/unix/trash.py
> +                yield None, mount_trash
```suggestion
                yield UserDetails(None, None), mount_trash
```

2024-10-30 13:12 UTC, Horofic commented on dissect/target/plugins/os/unix/trash.py
> +                            _user=user_details.user if user_details else None,
```suggestion
                            _user=user_details.user
```

2024-10-30 13:12 UTC, Horofic commented on dissect/target/plugins/os/unix/trash.py
> +                        _user=user_details.user if user_details else None,
```suggestion
                        _user=user_details.user

2024-11-04 11:03 UTC, Schamper requested changes

2024-11-04 11:03 UTC, Schamper commented on tests/plugins/os/unix/test_trash.py
> +)
```suggestion
```

2024-11-04 11:03 UTC, Schamper commented on tests/plugins/os/unix/test_trash.py
> +    assert len(list(plugin.trash())) == 11 * len(plugin.trashes)
```suggestion
    with patch.object(target_unix_users.fs, "mounts", {"/tmp/example": None, "/mnt/example": None}):
        target_unix_users.add_plugin(UnixPlugin)
        plugin = GnomeTrashPlugin(target_unix_users)
    
        assert sorted([str(t) for _, t in plugin.trashes]) == [
            "/home/user/.local/share/Trash",
            "/media/user/example/.Trash-1000",
            "/mnt/example/.Trash-1234",
            "/tmp/example/.Trash-5678",
        ]
    
        assert len(list(plugin.trash())) == 11 * len(plugin.trashes)
```

2024-11-04 11:03 UTC, Schamper commented on dissect/target/filesystem.py
> +
```suggestion
```

2024-11-04 11:03 UTC, Schamper commented on dissect/target/filesystem.py
> +    mounts: dict = {}
My last suggestion seems to work?

2024-11-12 12:47 UTC, Horofic submitted a review, later dismissed

2024-11-15 09:45 UTC, Horofic approved these changes

2024-11-15 15:22 UTC, Schamper requested changes

2024-11-15 15:22 UTC, Schamper commented on dissect/target/plugins/os/unix/trash.py
> +            for mount_trash in self.target.fs.path(mount_path).glob("**/.Trash-*"):
Are you sure? Doesn't this have the same behaviour? 

https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob

The documentation for `rglob` explicitly states it's basically the same as `.glob("**/<pattern>")`. Don't you mean `*/.Trash-*`?

2024-11-21 18:34 UTC, Schamper approved these changes

2024-11-22 10:04 UTC, merged