Support st_blksize and st_blocks on JFFS2
fox-it/dissect.target pull request #912
Opened 2024-10-17 16:01 UTC by twiggler

The block size  is a function of the "erase size" of the underlying flash device.
Linux stat reports the default block size, which is defined as 4k in libc. 

Also tried to implement missing nlink functionality as a bonus, but it exceeded the story budget. 
Will create issue for it after the weekend. 

Closes #819

2024-10-17 21:37 UTC, Schamper requested changes

2024-10-17 21:37 UTC, Schamper commented on dissect/target/filesystems/jffs.py
> +        st_info.st_blocks = (node.isize + 511) // 512 if self.is_file() else 0
Can you add a unit test for a directory entry?

2024-10-21 18:58 UTC, Schamper requested changes

2024-10-21 18:58 UTC, Schamper commented on tests/filesystems/test_jffs2.py
>          mode=33204,
```suggestion
        mode=0o100664,
```

2024-10-21 18:58 UTC, Schamper commented on tests/filesystems/test_jffs2.py
> +        mode=16893,
```suggestion
        mode=0o40775,
```

2024-10-22 08:25 UTC, Schamper approved these changes

2024-10-22 08:30 UTC, pyrco approved these changes

2024-10-22 08:35 UTC, merged