Allow RegfValue.type to fall back to int
fox-it/dissect.target pull request #956
Opened 2024-11-21 13:24 UTC by JSCU-CNI

This PR fixes edge cases where `RegfValue.type` cannot be translated to the `RegistryValueType` enum.

2024-11-21 14:01 UTC, Horofic commented
Would you mind adding a test case for this behaviour in `test_regutil`?

Not sure, but should this not return `REG_NONE` in this case? Took a cursory peek here https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types.

2024-11-21 14:02 UTC, Schamper commented
Using `_missing_` is probably nicer: https://docs.python.org/3/library/enum.html#enum.Enum._missing_

2024-11-26 13:53 UTC, Schamper requested changes

2024-11-26 13:53 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +    def type(self) -> RegistryValueType | int:
```suggestion
    def type(self) -> RegistryValueType:
```
No longer necessary.

2024-11-26 13:54 UTC, Schamper commented
> Added in [308fda1](https://github.com/fox-it/dissect.target/pull/956/commits/308fda1cb84d9ac2dd63087bb8af0032664740f8). Perhaps the Enum should be moved to the `dissect.regf` project?

Maybe, I'm fine with it in here for now since this enum serves more as an abstraction layer than a "parsing" enum.

2024-11-26 16:22 UTC, Schamper approved these changes

2024-11-26 22:16 UTC, Schamper approved these changes

2024-11-27 08:47 UTC, merged