Microsoft Office add-in detection
fox-it/dissect.target pull request #966
Opened 2024-12-05 12:41 UTC by twiggler

Detects:
- Persistence through startup folders (templates, executables)
- COM addins 
- VSTO addins by parsing ClickOnce Deployment manifests
- Web addins by inspecting WEF cache and parsing manifests

Limitations:
- Works on Office for Windows
- Supports Microsoft Office 2016 and later

Bonus:
- Fix issue in resolver where user environment was not taken into account when expanding paths
- Fix issue where partial path resolution resolved to directories.
- Added convenience functions for querying registry

2024-12-05 14:52 UTC, Schamper requested changes

2024-12-05 14:52 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +    def value_or_default(self, value: str, default: ValueType = None) -> RegistryValue:
Can you roll this into the `value` method so it's more in line with standard library Python code?

2024-12-05 14:52 UTC, Schamper commented on dissect/target/helpers/utils.py
> +    """Convert a single value or a list of values to a list. A value of `None` is converted to an empty list.
```suggestion
    """Convert a single value or a list of values to a list. A value of ``None`` is converted to an empty list.
```

2024-12-05 14:52 UTC, Schamper commented on dissect/target/plugins/os/windows/registry.py
> +    def key_or_empty(self, key: Optional[str] = None) -> KeyCollection:
Same with this one.

2024-12-05 15:37 UTC, twiggler commented on dissect/target/helpers/utils.py
> +def to_list(value: T | list[T] | None) -> list[T]:
To Michaël: For our usecases, your implementation won in the end.

2024-12-12 13:07 UTC, Horofic requested changes

2025-01-06 16:33 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        display_name = display_name_element.get("DefaultValue") if display_name_element is not None else None
No, see https://docs.python.org/3/reference/datamodel.html#object.__delitem__

2025-01-07 11:35 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        addin_path_tuples = itertools.product(self.HIVES, [self.OFFICE_KEY], self.OFFICE_COMPONENTS, [self.ADD_IN_KEY])
Tried but it gets messier IMO

2025-01-07 12:53 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +    def _machine_startup_folders(self) -> Iterable[str]:
> Can't OFFICE_COMPONENTS be reused here? 
We could eagerly create a map from component to root directory, but I am unsure if that is better. 

Added a union of string literals to prevent mistakes.

> I think this can also be consolidated in just the _office_install_root function

This got a bit messy.

Added memoization to avoid looking up multiple times.

2025-01-14 14:02 UTC, Horofic requested changes

2025-01-14 14:02 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +            return NativePluginStatus(loaded=False, load_behavior=LoadBehavior.Manual)
Wouldn't a `Dataclass` be a better approach for this? With the initial `loaded` and `load_behaviour` set to `None`. 

This this way you always return something, and avoids the `if None` checking in the `native()` function and potentially somewhere else.

2025-01-14 15:18 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        load_behavior = addin.value("LoadBehavior", None).value
No, it will return ``None`` because we are returning a RegistryValue with a value of ``None``.

(I do see that the ValueType type union was missing ``None``, added it, but that didn't cause runtime-errors)

2025-01-14 15:20 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +            return NativePluginStatus(loaded=False, load_behavior=LoadBehavior.Manual)
That would imply that either one of `loaded` and `load_behavior` can be ``None``, which cannot happen; either both values are present, or they are both absent.

So I think it is better to leave as-is.

2025-01-14 15:24 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +    def _parse_dependent_assembly(self, dependent_assembly: Element, cwd: Path) -> set[Assembly]:
AFAIK The function can return an empty set, but never a set with None values.

For maximum clarity I added a type hint to the empty sets

2025-01-15 09:58 UTC, Schamper requested changes

2025-01-15 09:58 UTC, Schamper commented on dissect/target/helpers/regutil.py
> +            return VirtualValue(VirtualHive(), value, default)
Wouldn't we still want the actual hive to be linked?

2025-01-15 09:58 UTC, Schamper commented on dissect/target/loaders/cb.py
> +    def _value(self, value: str) -> str:
Maybe update these return types while we're at it?

2025-01-15 09:58 UTC, Schamper commented on dissect/target/loaders/smb.py
> +    def _value(self, value: str) -> str:
Maybe update these return types while we're at it?

2025-01-15 09:58 UTC, Schamper commented on dissect/target/plugins/apps/productivity/msoffice.py
> +    @lru_cache(16)
Can you initialise this in the `__init__`? Search for other uses of `lru_cache` in the Dissect project for examples.

If you want context, hit me up offline.

2025-01-15 12:04 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +            return NativePluginStatus(loaded=False, load_behavior=LoadBehavior.Manual)
That's true, but you end up setting them to `None` anyway in the `OfficeNativeAddinRecord` anyway. So I thought the suggested approach would be a bit nicer.

2025-01-15 13:08 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +    @lru_cache(16)
Posted this in an earlier comment. Some more context can also be found here https://github.com/fox-it/dissect.target/pull/547!

2025-01-15 22:00 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +            return NativePluginStatus(loaded=False, load_behavior=LoadBehavior.Manual)
I appreciate the suggestion and agree that it is  clunky at the call-site.

However, I think it comes down to Python lacking an optional chaining operator such as in `status?.loaded`, 
and I would rather not trade invariants to compensate for that.

2025-01-16 07:37 UTC, twiggler commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        load_behavior = addin.value("LoadBehavior", None).value
>  Though, I wasn't aware it returned a RegisteryValue with a None value in it

Yeah IMO the pattern is different in that `value(.)` always is wrapped in the `RegistryValue` context. This incidentally also causes a stutter when using the API, i.e. `value(.).value`.

Interestingly how this relates to your suggestion here https://github.com/fox-it/dissect.target/pull/966#discussion_r1914865963, i.e. the difference between a value wrapped in an optional, and an optional embedded in a value.

I guess this can be resolved now.

2025-01-16 09:46 UTC, twiggler commented on dissect/target/loaders/cb.py
> +    def _value(self, value: str) -> str:
I love types, so happy to do it.

But is there light at the end of the tunnel? 

Unfortunately, a lot of the type annotations are incorrect. As I am used to inferring the behavior of a function by its type signature, this has put me on the wrong foot on multiple occasions. The type annotations are incorrect because the code is not type checked, either in CI or locally. I think one of the problems with enforcing type checking is that core dependencies such as flow record and cstruct use dynamic typing. 
I believe @Miauwkeru mentioned a solution for somehow adding type information to cstruct. Or we could use code generation at "compile-time" instead of during run-time. 

Happy to help out with this (also in my own time). However,  I also think a principled decision needs to be made to stop relying on techniques which use dynamic types.

2025-01-16 10:36 UTC, Schamper commented on dissect/target/loaders/cb.py
> +    def _value(self, value: str) -> str:
The `.pyi` generation for cstruct was indeed my idea, of which Miauwkeru made a POC. Happy to hear other suggestions of yours.

However, 95% of code in `dissect.target` does not interact with `flow.record` or `dissect.cstruct`, and we still want accurate type information there. I agree that it's best if we can check that in CI or locally. So I think the best way forward for the time being is to figure out if there's some way to do that and ignore all `flow.record` and `dissect.cstruct` types while we work separately on a solution for those dynamic types.

2025-01-23 12:25 UTC, twiggler commented on dissect/target/loaders/cb.py
> +    def _value(self, value: str) -> str:
(I take it the return type can be covariant?)

2025-01-29 11:27 UTC, Horofic requested changes

2025-01-29 11:29 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        Yields a OfficeNativeAddinRecord with fields:
bump

2025-01-29 11:29 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        Yields a OfficeNativeAddinRecord with fields:
bump

2025-01-29 11:30 UTC, Horofic commented on dissect/target/plugins/apps/productivity/msoffice.py
> +        Yields a OfficeWebAddinRecord with fields:
bump

2025-01-29 11:53 UTC, Horofic commented on dissect/target/plugins/os/windows/registry.py
> +    def keys(self, keys: Union[str, list[str]]) -> Iterator[RegistryKey]:
bump

2025-01-29 11:53 UTC, Horofic commented on dissect/target/plugins/os/windows/registry.py
> +    def values(self, keys: Union[str, list[str]], value: str) -> Iterator[RegistryValue]:
bump

2025-01-29 11:55 UTC, Horofic commented on tests/plugins/filesystem/test_resolver.py
> +from __future__ import annotations
bump

2025-01-30 09:16 UTC, Schamper approved these changes

2025-02-05 08:32 UTC, merged