Prevent enumerating entire non-ISO formatted syslog files in `is_iso_fmt`
fox-it/dissect.target pull request #972
Opened 2024-12-10 14:09 UTC by JSCU-CNI

This PR prevents `is_iso_fmt` from enumerating entire non-ISO formatted auth or syslogs.

2024-12-13 20:34 UTC, Schamper requested changes
Can you also add a unit test for this specific edge case

2024-12-13 20:34 UTC, Schamper commented on dissect/target/plugins/os/unix/log/helpers.py
> +            if isinstance(max_lines, int) and i > max_lines:
```suggestion
            if max_lines is not None and i > max_lines:
```

2024-12-17 09:48 UTC, Poeloe commented on dissect/target/plugins/os/unix/log/helpers.py
> +                    log.warning("No timestamp found in one of the lines in %s!", file)
Is it desired that you now only get debug messages and not a warning when the `max_lines` value is reached?

2025-01-30 10:36 UTC, Schamper commented
@Poeloe

2025-01-30 11:00 UTC, Poeloe approved these changes

2025-01-30 11:40 UTC, merged